### ISSUE TITLE
Lỗi - Treatment Vào form toa thuốc bị lỗi

### ISSUE THREAD

**Issue by lqbinh1987** [dhhiswork/Loi#101]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/12/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Thạnh Trị**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_thanhtri_122024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5432`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`NAS/DuLieuCongTy/Database/dbthanhtri_122024.rar`]

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `ALL` - _**MaKB**_: `ALL` - _**MaBA**_: `MaBA` _**NgayKCB**_: `19/12/2024` - _**MaPhong**_: `ALL` - _**MaDV**_: `18` - _**ThangKT**_: `12` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Hiện tại ở BV đang bị tình trạng **1 số Khoa** khi vào form Toa thuốc thì bị lỗi như hình dưới, trong code báo lỗi thì **mahh**, ở những khoa bị lỗi thì mỗi Khoa báo mã hàng hóa khác nhau.

Và Lưu ý thêm ở BV đã gõ phần mềm xóa thư mục cài đặt cái lại vẫn còn bị.
Trích dl nguyên tháng 12/2024 về kiểm tra thì không bị lỗi trên, như Hình dưới là lỗi ở BV, trích dl về lại không bị, và ở Bv cũng bị 1 số Khoa chứ không bị hết BV.
**Nhờ Tổ lập trình hỗ trợ.**

Phiên bản :2024.12.18.072406AM
Npgsql.NpgsqlException:
new row for relation "pstonkho" violates check constraint "pstonkho_chktamxuat"
Severity: ERROR
Code: 23514
   at DataAccess.Adapter.ToaThuocAdapter.reset_TamXuat(String pTenmay, String pTenmaywin, String pThangKT, String pNamKT, Int32 pDaCanKho, String pLoaiXN)
   at BusinessLogic.Classes.ToaThuoc.reset_TamXuat(String pTenmay, String pTenmaywin, String pThangKT, String pNamKT, Int32 pDaCanKho, String pLoaiXN)
   at HospitalTreatment.Forms.FrmRaToa.FrmRaToa_Load(Object sender, EventArgs e)
 update current.pstonkho set    tamxuat      =  coalesce(tamxuat,0)    + (-3) where **mahh  = 'CE247'**   and giavat   =  5179.999996   and giaxuat  =  5179.999996   and coalesce(handung,'') = '04/2027'   and coalesce(solo,'') = '010424'   and thangkt = '12'   and namkt   = '2024'   and xoa     = 0    and upper(khocp)   = '03'   and coalesce(madv,'') = '
![image](https://github.com/user-attachments/assets/1ef62773-0c7a-420e-a8b0-0eeb0ddf6d30)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>
  
  ---
  
  - **📘 Mô tả thực hiện:**
    - [ ] ***Theo luồng công việc này.*** 
  
  - **⏳ Thời gian hoàn thành:** **_2024-12-20_** 
  
  - **🧑‍💻 Thực hiện:** @vuongdh 
  
  ---
  
  <sup>**📢Lưu ý tiếp nhận:**</sup>
  <sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
  <sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
  <sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
  <sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>
  <sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by vuongdh** [comment]
✔️ Tiếp nhận và thực hiện công việc
⏳ Thời gian hoàn thành: 2024-12-20

**Comment by lqbinh1987** [comment]
📢 TRAO ĐỔI📢
---------------------------------------------------------------------
-  👉 **Assign**: @vuongdh 
-  📘 **Nội dung**: Tranh thủ dùm em chổ này nhe anh, nhiều BV bị, có máy bị máy không, khi đã bị lỗi đó rồi, thì đóng lỗi lại chọn toa thuốc cũ cũng không hiển thị thông tin gì luôn.

**Comment by vuongdh** [comment]
📢 TRAO ĐỔI📢
👉 Assign: @lqbinh1987 
📘 Nội dung: Anh đang kiểm tra

**Comment by vuongdh** [comment]
@lqbinh1987 Anh test không lỗi ta

![](https://i.imgur.com/lra59Wb.gif)

**Comment by vuongdh** [comment]
Test theo mã hàng em báo 

![](https://i.imgur.com/K7r4MQd.gif)

**Comment by lqbinh1987** [comment]
📢 TRAO ĐỔI📢
---------------------------------------------------------------------
-  👉 **Assign**: @vuongdh 
-  📘 **Nội dung**: DL trích về test không ra lỗi anh, ở BV mới vào form toa thuốc là bị lỗi rồi. Mà ở BV thì máy bị máy không, chứ không bị hết.

**Comment by vuongdh** [comment]
Vậy em coi tạm xuất có bị âm không?

**Comment by vuongdh** [comment]
Check tạm xuất không cho âm nên lỗi. Xử lý cái tạm xuất. Hoặc vào file tạm (coi máy tính đó cấu hình tên là gì, xóa hết các dữ liệu tạm của máy đó). Bảng: current.tkdatatemp

**Comment by lqbinh1987** [comment]
🐛  **Đã fix lỗi**
-Test lần: 1
![image](https://github.com/user-attachments/assets/476497c4-2a35-4088-a948-21e6d3553280)
