### ISSUE TITLE
Lỗi - Prescription: Bảng kê Tổng hợp theo đối tượng tủ trực thống kê thiếu đối tượng KSK và khác

### ISSUE THREAD

**Issue by chauthanhtra** [dhhiswork/Loi#106]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **23/12/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `51014`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Quảng Ngãi**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_quangngai_xuatkhac_nxttt_treat_23122024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5432`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/QKMHrcx1X)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024021779` - _**MaKB**_: `2411003319` - _**MaBA**_: `MaBA` _**NgayKCB**_: `11/11/2024` - _**MaPhong**_: `A1-08` - _**MaDV**_: `10` - _**ThangKT**_: `11` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `02` - _**TuTruc**_: `CC` - _**MaHH**_: `MaHH` - _**SoHD**_: `K51.00015/11` - _**NgayHD**_: `11/11/2024` - _**ThangKT**_: `11` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Lỗi Ghi Lại: https://github.com/dh-hos/dhg.hospitalprescription/issues/229

- Quản lý tủ trực trên Prescription -> Thống kê theo đối tượng hiện tại chỉ hiển thị các đối tượng BHYT, Trẻ em, Thu phí, Miễn phí -> thiếu các đối tượng khác như Khám sức khỏe và Khác
- Khi in ra thì có thêm cột đối tượng Khác
    -> Cột tổng cộng tính số lượng đủ nhưng cộng chi tiết theo từng đối tượng thì thiếu số lượng so với tổng cộng do không hiển thị số lượng thuốc của các đối tượng KSK và khác
    => Thêm cột khác vào form thống kê để tính số lượng các đối tượng KSK và khác và hiển thị số lượng thuốc đối tượng KSK và Khác vào cột khác trên trang in

![](https://i.imgur.com/FD7mgRD.png)
![](https://i.imgur.com/1BM90a3.png)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>
  
  ---
  
  - **📘 Mô tả thực hiện:**
    - [ ] ***Theo luồng công việc này.*** 
  
  - **⏳ Thời gian hoàn thành:** **_2024-12-26_** 
  
  - **🧑‍💻 Thực hiện:** @lequocthong29 
  
  ---
  
  <sup>**📢Lưu ý tiếp nhận:**</sup>
  <sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
  <sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
  <sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
  <sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>
  <sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-12-26.

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm Prescription 30/12/2024
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Phần mềm đã fix lỗi Bảng kê theo đối tượng tủ trực thiếu đối tượng KSK và Khác

- Hình ảnh: 

![](https://i.imgur.com/rvAMJDq.png)
![](https://i.imgur.com/ImafirE.png)

***

**Comment by chauthanhtra** [comment]
### ✅ **HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
