### ISSUE TITLE
Lỗi - không có mã QR trong thiết kế trang in phiếu tạm ứng.

### ISSUE THREAD

**Issue by nqhoa1005** [dhhiswork/Loi#11]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92004`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV ĐKTP Cần Thơ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_dktpct_102024092024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/m7Ir4G614)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024065909` - _**MaKB**_: `MaKB` - _**MaBA**_: `032311` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `43` - _**ThangKT**_: `10` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

- **Tham số tamungtuin chỉ có 2 giá trị 0 và 1**, khi bật là 1 thì lúc in phiếu tạm ứng phần mềm vẫn không hiển thị bảng xác nhận thiết kế trang tạm ứng, nhưng khi bật bằng 2 thì mới hiển thị bảng hỏi có thiết kế hay không, bấm đồng ý vô trang thiết kế thì không thấy  para như thiết kế phiếu thu.
**Trường hợp này xảy ra đối với 2 BV: ĐKTP CT - 92004 và Sản Nhi TV 84133**
![image](https://github.com/user-attachments/assets/8a46113f-44ca-48ea-92b1-fa061bdb34b2)
![image](https://github.com/user-attachments/assets/fe020388-5e03-40c4-a158-6c9f49f2ebf2)
-------------
- Còn đối với TTYT TP Quãng Ngãi 51014  thì thiết kế ok, nhưng khi in tạm ứng, hiện bảng hỏi thiết kế, bám bỏ qua thì phần mềm nín thin không in ra được phiếu tạm ứng.
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_quanngai_bangkebhyt_donvicuoi_15102024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/glX2UBC4l)
-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023001120` - _**MaKB**_: `2410002935` - _**MaBA**_: `` _**NgayKCB**_: `09/10/024` - _**MaPhong**_: `A1=29` - _**MaDV**_: `10` - _**ThangKT**_: `10` - _**NamKT**_: `2024`

CLip mô tả lỗi:

https://github.com/user-attachments/assets/b22bf2c7-0640-4934-8da8-7e8d13f1eb14
---
Tạo lại theo https://github.com/dh-his/Ghi_Nhan_Loi/issues/16

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Thực hiện chỉnh lỗi trên site mới [code-dh-hospital-training](https://github.com/code-dh-hospital-training)._**

- **⏳ Thời gian hoàn thành:** **_2024-11-20_** 

- **🧑‍💻 Thực hiện:** @nqhoa1005 

---

<sup>**📢Lưu ý tiếp nhận:**</sup>
<sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
<sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
<sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
<sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Fees.exe v.3.24.1119.1 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FFeesexe%2F32411191-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FFeesexe%2F32411191-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FFeesexe%2F32411191-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ☑: https://github.com/dhhiswork/Loi/issues/11

- 🐛: Lỗi - không có mã QR trong thiết kế trang in phiếu tạm ứng. ![](https://i.imgur.com/yENn7i2.png)
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Fees.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @lqbinh1987 
- **📘 Nội dung:** Kiểm tra lại luồng công việc này

**Comment by lqbinh1987** [comment]
💡KIỂM TRA SẢN PHẨM💡
***
Assignees: @tolaptrinh-issue 
Mô tả lỗi:
Đối với mã BV 92004 thì đã ok, bật tham số **tamungtuin=1**, thì thiết kế có các para QR.
Nhưng còn mã BV **84133** thì vân bị tình trạng bật **tamungtuin=1** thì lúc in phiếu tạm ứng phần mềm vẫn không hiển thị bảng xác nhận thiết kế trang tạm ứng, nhưng khi bật bằng 2 thì mới hiển thị bảng hỏi có thiết kế hay không, bấm đồng ý vô trang thiết kế thì không thấy các para QR như phiếu thu.
![image](https://github.com/user-attachments/assets/569e46eb-df7f-4902-ba9d-52c3f72d4652)
![image](https://github.com/user-attachments/assets/705b9002-96aa-4290-ba18-1d772c00c4c8)



***
Thông tin bệnh nhân(nếu có)
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_bvsn1`
- ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) (NAS/DuLieuCongTy/Database/binh_bvsn12024000001_2412000001_2024000001.rar)
-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024000001` - _**MaKB**_: `MaKB` - _**MaBA**_: `2024000001` _**NgayKCB**_: `` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `08` - _**ThangKT**_: `12` - _**NamKT**_: `2024`

***
❌ Không thể tiếp tục kiểm tra sản phẩm, **tạm dừng kiểm tra.**

**Comment by nqhoa1005** [comment]
- ✔️ **Tiếp nhận công việc** 
- 📖 Mô tả thực hiện : Check theo mã đơn vị 84133
- 📆 Thời gian hoàn thành dự kiến : **2024-12-13**

**Comment by nqhoa1005** [comment]
❗❗ **TRAO ĐỔI** ❗❗

---
👉 @lqbinh1987 

![image](https://github.com/user-attachments/assets/fc29ff1d-93f5-4ef4-881a-d3d4884520c5)

**Comment by lqbinh1987** [comment]
💡 TRAO ĐỔI💡
---------------------------------------------------------------------
-  👉 **Assign**: @nqhoa1005 
-  📘 **Nội dung**: port 5432

**Comment by nqhoa1005** [comment]
✅ HOÀN THÀNH

---

- Bổ sung para QRCode cho 84133

![](https://i.imgur.com/6zMDOxX.png)
![](https://i.imgur.com/Hnk34QX.png)

---
- ⏯️ Chờ upload bản mới

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @lqbinh1987 
- **📘 Nội dung:** Cập nhật Fees.exe v.3.24.1212.0

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by lqbinh1987** [comment]
✅ **Đã hỗ trợ**
-Test lần: 1
![image](https://github.com/user-attachments/assets/5afbe0f9-6609-45b7-b7a8-0675a5e332b9)
