### ISSUE TITLE
Lỗi - Treo module khi bấm menu Khám bệnh.

### ISSUE THREAD

**Issue by lqbinh1987** [dhhiswork/Loi#13]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `ALL`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **ALL**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_huyethoc_cantruthuoctrasai`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5432`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/0T8OweKLu)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Bấm menu Khám bệnh 1 lần, đợi nó load lên form thì được, nhưng trong khi form chưa mở lên được mà bấm chuột thêm lần nữa vào bất kỳ menu nào là phần mềm treo luôn.
**Lưu ý là dữ liệu đang test là cho chọn phòng khám, đối với những DL không chọn phòng khám cũng bị luôn.**
![image](https://github.com/user-attachments/assets/45b30e17-3d78-4b8c-9fff-4eb757b5c1e5)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Kiểm thử xác nhận thông tin lỗi, thử trên nhiều dữ liệu khác xem có bị trường hợp này hông._**

- **⏳ Thời gian hoàn thành:** **_2024-11-19_** 

- **🧑‍💻 Thực hiện:** @nqhoa1005 

---

<sup>**📢Lưu ý tiếp nhận:**</sup>
<sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
<sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
<sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
<sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>

**Comment by nqhoa1005** [comment]
❗❗ **XÁC ĐỊNH ĐƯỢC LỖI** ❗❗
- Test trên các dữ liệu đều bị tương tự
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_huyethoc_cantruthuoctrasai`
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_dktpct_102024092024`
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_hongngu_yhct_19112024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`

✳️Thao tác double click vào menu Khám bệnh gây ra treo module
- [clip test](https://gofile.me/78TQg/mDTsBW20x)

**Comment by nqhoa1005** [comment]
- ✔️ **Tiếp nhận công việc** 
- 📖 Mô tả thực hiện : Thực hiện chỉnh lỗi theo luồng công việc
- 📆 Thời gian hoàn thành dự kiến : **2024-11-20**

**Comment by nqhoa1005** [comment]
✅ HOÀN THÀNH

---
- ⏯️ anh @tolaptrinh-issue check dùm em

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @nqhoa1005 
- **📘 Nội dung:** Xử lý thêm, nếu đã waiting ở menu rồi, thì load form không cần waiting nữa.

**Comment by nqhoa1005** [comment]
✅ HOÀN THÀNH
👉 Đã xử lý lại không waiting khi mở form

---
- ⏯️ anh @tolaptrinh-issue

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @nqhoa1005 
- **📘 Nội dung:** Đồng ý.

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue </sup>

**Comment by nqhoa1005** [comment]
✅ HOÀN THÀNH

![Huyết học CT](https://www.dropbox.com/scl/fi/4i0bvdvtnixxkwm7aimhr/Prescription.vshost_nbMThNO8mo.mp4?rlkey=cyvk0prarixa2t8p0zk3azwk8&dl=0)

![ĐKTP CT](https://www.dropbox.com/scl/fi/4asbvp0l4yo794j0rh5uk/Prescription.vshost_SxQT9LwsGO.mp4?rlkey=kaao1t1yo2cupj18y80y1bz3c&dl=0)


---
- ⏯️ Chờ upload bản mới

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Prescription.exe v.3.24.1125.2 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32411252-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32411252-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32411252-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: `Fix lỗi - Treo module khi bấm menu Khám bệnh`

- ![](https://www.dropbox.com/scl/fi/7v4ydp0padkmkssvb6p9i/Prescription.vshost_VmddO9aght.mp4?rlkey=z0f5j8rd991qdnwo8xb55724x&dl=0)

- ☑: `https://github.com/dhhiswork/Loi/issues/13`
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Prescription.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Prescription.exe v.3.24.1125.3 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32411253-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32411253-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32411253-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: `Fix lỗi - Treo module khi bấm menu Khám bệnh`

- ![](https://www.dropbox.com/scl/fi/7v4ydp0padkmkssvb6p9i/Prescription.vshost_VmddO9aght.mp4?rlkey=z0f5j8rd991qdnwo8xb55724x&dl=0)

- ☑: https://github.com/dhhiswork/Loi/issues/13
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Prescription.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by lqbinh1987** [comment]
🐛  Đã fix lỗi

Clip test lần 1:

https://github.com/user-attachments/assets/24d13098-05b0-432e-8103-ded5a6895044
