### ISSUE TITLE
Lỗi - Treatment: BV Ô Môn Treatment mất hình ảnh phẫu thuật/thủ thuật khi xem/in lại phiếu PT/TT nếu đóng form mở lại

### ISSUE THREAD

**Issue by chauthanhtra** [dhhiswork/Loi#15]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **15/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92007`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Ô Môn**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_omon_anhsinhthiet_ttpt_treat_15112024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/nGG5gz6t1)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2018055825` - _**MaKB**_: `2411012392` - _**MaBA**_: `2024015188` _**NgayKCB**_: `14/11/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `11` - _**ThangKT**_: `11` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Bệnh nhân nội trú lập phiếu PT/TT có lưu hình ảnh PT/TT sau khi đóng form mở lại thì mất hình ảnh PT/TT không xem hay in phiếu PT/TT có hình được , hình ảnh có lưu trong thư mục hình và đường dẫn trong dữ liệu (lúc mới lưu thì xem, in được bình thường)

 ![](https://i.imgur.com/Yghfm2J.gif)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-11-22_** 

- **🧑‍💻 Thực hiện:** @vuongdh 

---

<sup>**📢Lưu ý tiếp nhận:**</sup>
<sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
<sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
<sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
<sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận.
⌛ Thời gian hoàn thành dự kiến: 2024-11-25

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Treatment.exe v.4.24.1125.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42411250-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42411250-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42411250-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Lỗi - Treatment: BV Ô Môn Treatment mất hình ảnh phẫu thuật/thủ thuật khi xem/in lại phiếu PT/TT nếu đóng form mở lại #15

- Cập nhật: bảo đảm tài khoản người dùng kết nối được với thư mục chứa ảnh (Do không kết nối được thư mục trên server, tạo thự mục mới có thể truy xuất được)

![2024-11-25_10-32-16](https://github.com/user-attachments/assets/ec205656-cedd-4991-b280-cb17e4daa014)


- ☑: https://github.com/dhhiswork/Loi/issues/15
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Treatment.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### ✔️ **ĐÃ TIẾP NHẬN**
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '29/11/2024'.
***

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm Treatment.exe v.4.24.1125.1
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Treatment đã fix lỗi mất hình ảnh phẫu thuật/thủ thuật khi xem/in lại phiếu PT/TT nếu đóng form mở lại

- Hình ảnh: 

![](https://i.imgur.com/QgJlPs5.gif)

***

### 🆘 **Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.**

- Diễn giải lỗi:
  - Lỗi khi chỉnh phiếu PT/TT đổi sang ảnh khác
- Hình ảnh lỗi:

![](https://i.imgur.com/ocThnpv.gif)

***
Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### ❎ **CHƯA HOÀN THÀNH**
- Hoàn thành kiểm tra
- Phần mềm chưa đáp ứng đúng yêu cầu.
- Yêu cầu Tổ coder kiểm tra lại.
-

**Comment by vuongdh** [comment]
@chauthanhtra lỗi này là do KHÔNG có quyền truy cập hoặc chọn ảnh đang sử dụng

**Comment by vuongdh** [comment]
@chauthanhtra theo hình ảnh báo lỗi --> chọn ảnh đang được sử dụng --> nên khi lưu không ghi đè  được

**Comment by chauthanhtra** [comment]
Anh @vuongdh 
Nhìn hình giống nhưng 2 hình khác nhau. Em có thử với ảnh khác cũng vậy. Ảnh được chọn là trên máy em nên có full quyền, thư mục lưu ảnh máy chủ máy em cũng có quyền thêm sửa xóa

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm Treatment.exe v.4.24.1125.1
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Treatment đã thêm và chỉnh được ảnh phiếu PT/TT

- Hình ảnh: 

![](https://i.imgur.com/BJaUrKL.gif)

***

**Comment by chauthanhtra** [comment]
### ✅ **HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
