### ISSUE TITLE
Lỗi - BV Ung Bướu: Fees Bảng kê bệnh nhân nợ viện phí tính sai số tiền nợ khi bệnh nhân được miễn cùng tri trả

### ISSUE THREAD

**Issue by tolaptrinh-issue** [dhhiswork/Loi#17]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **12/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92086`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Ung Bướu**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_ungbuou_nochiphi_12112024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/3lQRR5j6Q)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023057368` - _**MaKB**_: `2410011776` - _**MaBA**_: `022056` _**NgayKCB**_: `12/11/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `05` - _**ThangKT**_: `11` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Bệnh nhân có miễn cùng chi trả đã đóng hết số tiền cần trả nhưng phần mềm Fees báo bệnh nhân còn nợ chi phí. số tiền nợ là số tiền BH bệnh nhân được miễn cùng chi trả

![](https://i.imgur.com/EYplPjy.png)
![](https://i.imgur.com/WBvG7yJ.png)
![](https://i.imgur.com/EMa7jKN.png)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** 
  - Thực hiện cập nhật lại thông tin lỗi
  - Tiến hành chỉnh lỗi trên [code-dh-hospital-training](https://github.com/code-dh-hospital-training)

- **⏳ Thời gian hoàn thành:** **_2024-11-22_** 

- **🧑‍💻 Thực hiện:** @nqhoa1005 

---

<sup>**📢Lưu ý tiếp nhận:**</sup>
<sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
<sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
<sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
<sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>

**Comment by nqhoa1005** [comment]
✅ HOÀN THÀNH
![](https://i.imgur.com/u44MYDe.png)

---
- ⏯️ Chờ xác nhận từ @tolaptrinh-issue

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @nqhoa1005 
- **📘 Nội dung:** ***Nội dung phân việc thứ nhất chưa hoàn thành nhé***

**Comment by nqhoa1005** [comment]
✅ HOÀN THÀNH
👉 Đã cập nhật lại thông tin chi tiết về lỗi

---
- ⏯️ anh @tolaptrinh-issue

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @nqhoa1005 
- **📘 Nội dung:** Xử lý vậy chưa đạt yêu cầu tổng thể, không xử lý trường hợp bệnh nhân có miễn cùng chi trả, nhưng có những chi phí không thuộc miễn chi tra do điều kiện ngày miễn chi trả không thỏa điều kiện. Xử lý thêm trường hợp này.

**Comment by nqhoa1005** [comment]
- ✔️ **Đã tiếp nhận** 
- 📖 Mô tả thực hiện : Xử lý thêm điều kiện ngày bắt đầu - ngày kết thúc miễn cùng chi trả cho từng chi phí

**Comment by chauthanhtra** [comment]
✨CẬP NHẬT THÔNG TIN BÁO LỖI✨

Thông tin lỗi đã báo bị thiếu thông tin lỗi của BV Ung Bướu (sai form chức năng, BV báo lỗi form Theo dõi chi phí bệnh nhân nội trú)

- Bổ sung thêm lỗi form Theo dõi chi phí bệnh nhân nội trú tính sai số tiền khi bệnh nhân được miễn cùng tri trả
-> Lỗi ở 2 form bị lỗi: Theo dõi chi phí bệnh nhân nội trú và Bảng kê bệnh nhân nợ viện phí

![](https://i.imgur.com/jFozb6M.png)
![](https://i.imgur.com/9r7J0IL.png)
![](https://i.imgur.com/wLSZE3C.png)

***
Nếu cần ghi git mới thì code thông báo

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @nqhoa1005 
- **📘 Nội dung:** Xem luôn theo luồng công việc này.

**Comment by nqhoa1005** [comment]
✅ HOÀN THÀNH
👉 Báo cáo Bệnh nhân nợ viện phí tính sai số tính bệnh nhân còn nợ
![](https://i.imgur.com/L6HJt7J.png)
![](https://i.imgur.com/3tphU5A.png)
![](https://i.imgur.com/Ks40qJP.png)
---
- ⏯️ Xử lý tiếp báo cáo Theo dỗi chi phí bệnh nhân 
- 🕐 Thời hạn hoàn thành dự kiến : 2024-11-28

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Fees.exe v.3.24.1125.1 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FFeesexe%2F32411251-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FFeesexe%2F32411251-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FFeesexe%2F32411251-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Fees Bảng kê bệnh nhân nợ viện phí tính sai số tiền nợ khi bệnh nhân được miễn cùng tri trả

- ![](https://i.imgur.com/L6HJt7J.png) ![](https://i.imgur.com/3tphU5A.png) ![](https://i.imgur.com/Ks40qJP.png)

- ☑: https://github.com/dhhiswork/Loi/issues/17
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Fees.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### ✔️ **ĐÃ TIẾP NHẬN**
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '29/11/2024'.
***

**Comment by nqhoa1005** [comment]
✅ HOÀN THÀNH
---
👉 Bảng kê > Nội trú > Theo dỗi chi phí điều trị tính sai số tiền bệnh nhân còn nợ 

![](https://i.imgur.com/O2u5MvM.png)

---
- ⏯️ Chờ upload bản mới

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @nqhoa1005 
- **📘 Nội dung:** Thông tin báo lỗi 2 form, mới được có 1 form mà. Xem tiếp form còn lại. ![](https://i.imgur.com/KbnDgWU.png)

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @nqhoa1005 
- **📘 Nội dung:** Kiểm tra tổng thể lại các form đã thực hiện nhé. Cụ thể: lấy một dữ liệu full so sánh kết quả trước và sau chỉnh sửa nhé, để đảm bảo hông ảnh hưởng tới tổng thể. Dữ liệu có một bệnh nhân hông có ý nghĩa

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by nqhoa1005** [comment]
❗❗ **TRAO ĐỔI** ❗❗
- 👉  anh @tolaptrinh-issue do Git báo form lỗi là form Bệnh nhân nợ viện phí em đã fix xong có báo trước hoàn thành nên Form sau em post sau nên nội dung hoàn thành cho cmt sau chỉ có form Theo dỗi chi phí điều trị
![](https://i.imgur.com/DysOgCB.png).
- 👉 Hình ảnh em chụp là chứng minh đã fix xong, còn qui trình trước khi push code và báo hoàn thành em đều kiểm tra xuất thử trên nhiều dữ liệu rồi, nếu có lỗi hoặc kết quả sai sẽ check lại thì mới báo hoàn thành. VD Git này em cũng đã chạy thử dữ liệu của ĐKTP CT và Thạnh Trị có nhiều dữ liệu, và check luôn các form nếu có sử dụng cho Ngoại trú, BANT và nội trú riêng thì cũng chạy hết thử lại trước

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @nqhoa1005 
- **📘 Nội dung:** Ok. Khi có thử thì chụp hình lại đưa lên luôn, để mình khỏi kiểm tra lại.

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST 1**
***
Phần mềm Fees.exe v.3.24.1126.0
***

### 🆘 **Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.**

- Diễn giải lỗi:
  - Test dữ liệu bệnh nhân khác Bảng kê bệnh nhân nợ viện phí phần mềm tính sai số tiền Phát sinh thực tế BHYT
  - Chưa có phần mềm fix lỗi form Theo dõi chi phí bệnh nhân nội trú
- Hình ảnh lỗi:
![](https://i.imgur.com/d69sZWh.png)
![](https://i.imgur.com/K7Ey9zK.png)
![](https://i.imgur.com/UPoZhXs.png)
![](https://i.imgur.com/NdXvV1Z.png)

![](https://i.imgur.com/1JoEqrO.png)

***

Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### ❎ **CHƯA HOÀN THÀNH 1**
- Hoàn thành kiểm tra
- Phần mềm chưa đáp ứng đúng yêu cầu.
- Yêu cầu Tổ coder kiểm tra lại.

**Comment by nqhoa1005** [comment]
- ✔️ **Tiếp nhận công việc** 
- 📖 Mô tả thực hiện : Kiểm tra cột BHYT tại form Bảng kê bệnh nhân nợ chi phí
- 📆 Thời gian hoàn thành dự kiến : **2024-12-06**

**Comment by nqhoa1005** [comment]
❗❗ **TRAO ĐỔI** ❗❗

---

👉 @chauthanhtra 
✔️  Trường hợp sai cột BHYT tại form Bảng kê bệnh nhân nợ viện phí đã xác định được chổ sai và xử lý được.


❌  Còn trường hợp tính sai số tiền tại form Bảng kê theo dỗi chi phí bệnh nhân nội trú do dữ liệu hiện tại máy chủ chính đang lỗi oid khi thu phiếu thu để test phát sinh lỗi không cập nhật lại được công nợ không thực hiện kiểm tra chính xác được

👉 Đã test lại trên dữ liệu khác dữ liệu full trên 3 hồ sơ không xảy ra trường hợp **tính sai số tiền tại form Bảng kê theo dỗi chi phí bệnh nhân nội trú**
![image](https://github.com/user-attachments/assets/3556e6e8-307a-43ef-bb0f-3786e8dea308)
![image](https://github.com/user-attachments/assets/57dc4e0c-1286-4e64-b3a9-35020e8c9af0)
![image](https://github.com/user-attachments/assets/840f8b4d-58b9-4267-a40b-c4b6b664c911)

Check lại bảng kê theo dỗi chi phí bệnh nhân nội trú
![image](https://github.com/user-attachments/assets/ed4c95be-43fd-45d6-8a16-e4a8cb418865)
![image](https://github.com/user-attachments/assets/f80d091e-245c-4bc0-a397-aa40d1831f2e)

---

👉 @chauthanhtra nhờ hỗ trợ test lại tái hiện lại dùm trường hợp sai trên máy chủ khác để xác định chính xác điều kiện gây sai.

- Dùng thông tin dữ liệu sau hoặc bất kỳ dữ liệu nào có nhiều dữ liệu để kiểm chính xác hơn
✴️ Thông tin dữ liệu :

✅ Host : 192.168.50.60
- ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_thanhtri_1309` 
- ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5432` 

👉 Bệnh nhân đã test (có thêm 2 BA khác đã test cùng khoa)
-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
> _**MaBN**_: `2012011844` -_**MaKB**_: `2409003554` - _**MaBA**_: `2024007295` - _**NgayKCB**_: `11/09/2024` - _**MaPhong**_: `N2` - _**MaDV**_: `02` - _**ThangKT**_: `09` - _**NamKT**_: `2024`

**Comment by chauthanhtra** [comment]
### ✔️ **ĐÃ TIẾP NHẬN**
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '12/12/2024'.
***

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm Fees.exe v.3.24.1210.0
***
### 🆘 **Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.**

- Diễn giải lỗi:
  - Fees mới vẫn còn lỗi , bệnh nhân bệnh án nội trú lập bệnh án -> thu tạm ứng trước -> chỉ định CLS, thuốc -> xuất viện
  -  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_qdy_ct_full_05122024`
  -  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5432`
  -  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2020005917` - _**MaKB**_: `2412001591` - _**MaBA**_: `2024006362` _**NgayKCB**_: `12/12/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `01` - _**ThangKT**_: `12` - _**NamKT**_: `2024`

- Hình ảnh lỗi:
![](https://i.imgur.com/6GPNYML.png)
![](https://i.imgur.com/z0TbBGQ.png)
![](https://i.imgur.com/6NKPacs.png)
![](https://i.imgur.com/PBQsv30.png)
![](https://i.imgur.com/SJ8nlY3.png)
![](https://i.imgur.com/Vn8g4HK.png)

***
Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by nqhoa1005** [comment]
- ✔️ **Tiếp nhận công việc** 
- 📆 Thời gian hoàn thành dự kiến : **2024-12-16**

**Comment by chauthanhtra** [comment]
### ⁉️ **THẢO LUẬN**
***
- Nhờ code kiểm tra lại xem phần mềm Fees sai ở thao tác hay thông tin như tạm ứng, công nợ,...

**Comment by nqhoa1005** [comment]
✅ HOÀN THÀNH

---

- Bảng kê bệnh nhân nợ viện phí
![](https://i.imgur.com/hbf00Qz.png)

- Bảng kê Theo dỗi chi phí điều trị nội trú
![](https://i.imgur.com/aWEOIP0.png)

---
- ⏯️ @chauthanhtra chờ upload bản mới

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Fees.exe v.3.24.1213.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FFeesexe%2F32412130-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FFeesexe%2F32412130-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FFeesexe%2F32412130-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi
Merge pull request #2 from code-dh-hospital-training/main

- 🐛: Bảng kê bệnh nhân nợ viện phí tính sai cột BHYT, Bảng kê Theo dỗi chi phí điều trị nội trú tính sai số tiền Bệnh nhân còn nợ

- ☑: https://github.com/dhhiswork/Loi/issues/17

- 📕: Thêm điều kiện để xác định các chi phí được miễn cùng chi trả cho nội trú tại AdaptersV2.GetCPhiCongNoBN

- Bảng kê Theo dỗi chi phí điều trị nội trú

![](https://i.imgur.com/aWEOIP0.png)
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40web--flow-informational?logo=github)](https://github.com/web-flow) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Fees.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm Fees.exe v.3.24.1218.0
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Phần mềm Fees đã fix lỗi báo cáo Bảng kê bệnh nhân nợ viện phí và Theo dõi chi phí bệnh nhân nội trú
  - Đã check trên dữ liệu BV khác, gửi phần mềm bv Ung Bướu theo dõi (BV không cho dữ liệu full)

- Hình ảnh: 
  - Dữ liệu BV QDY CT
![](https://i.imgur.com/Cul26VS.png)
![](https://i.imgur.com/nCZhFU3.png)
![](https://i.imgur.com/Il6gIO9.png)

  - Dữ liệu BV Ung Bướu
![](https://i.imgur.com/3baEkDr.png)
![](https://i.imgur.com/iNvY6MY.png)
![](https://i.imgur.com/TXzZfNE.png)

**Comment by chauthanhtra** [comment]
### ✅ **HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành gửi phần mềm cho khách hàng theo dõi do khách hàng không cho được dữ liệu full (chính sách BV).
