### ISSUE TITLE
Lỗi - Prescription BANT Theo đợt không lấy được tên chẩn đoán chính

### ISSUE THREAD

**Issue by hvtuan1987** [dhhiswork/Loi#18]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87164`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Phục hồi chức năng Đồng Tháp**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dphcn_01kcb_chandoan`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/cbbs0BMZl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023001896` - _**MaKB**_: `2410001987` - _**MaBA**_: `N2024000848` _**NgayKCB**_: `19/11/2024` - _**MaPhong**_: `NG` - _**MaDV**_: `VL` - _**ThangKT**_: `11` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Bệnh án ngoại trú theo đợt khi in bảng kê 01KCB thì tên chẩn đoán chính không hiển thị được.
Đã kéo các para như hình dưới vào nhưng vẫn không lấy được. Nhưng trong Para Tên bệnh kèm theo thì lại có tên Chẩn đoán chính và chẩn đoán bệnh kèm theo như hình dưới
![image](https://github.com/user-attachments/assets/5bee67e3-fa5c-46d8-9b4c-daacdcd3974f)

Hình khi xem Tổng kết chi phí
![image](https://github.com/user-attachments/assets/4f50e9c5-d06d-497f-9734-9e53e0ed6a6d)

Hình in ra bảng kê 01KCB không lấy được tên chẩn đoán chính riêng mà nằm ghép trong para Tên bệnh kèm theo
![image](https://github.com/user-attachments/assets/96a7218b-9ef5-445c-a47a-014f3b528041)

**Comment by hvtuan1987** [comment]
@tolaptrinh-issue Đã thử bản Prescription phiên bản 3.24.1119.3 vẫn chưa được !

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận và Thực hiện công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-11-22_** 

---

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Prescription.exe v.3.24.1125.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32411250-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32411250-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32411250-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Lỗi - Prescription BANT Theo đợt không lấy được tên chẩn đoán chính ![](https://i.imgur.com/PRwxeCV.png)

- ☑ : https://github.com/dhhiswork/Loi/issues/18
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Prescription.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by hvtuan1987** [comment]
-  ✔️ **Xác nhận** 
-Prescription đã Fix lỗi trên
![image](https://github.com/user-attachments/assets/3ed7a504-eb40-4dbe-8d60-8e8d202ee2d0)
