### ISSUE TITLE
Lỗi - HRM không lấy sai số ngày nghỉ phép năm

### ISSUE THREAD

**Issue by hvtuan1987** [dhhiswork/Loi#19]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **20/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `95006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TRUNG TÂM Y TẾ HUYỆN PHƯỚC LONG**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbphuoclong_hrm789`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/R6NrgJ6Du)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![Chi tiết nhân viên](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaNV**_: `381` _**MaDV**_: `10` - **NamKT**_: `2024`

HRM tính sai số ngày phép năm của nhân viên năm 2024 do nhân viên trong tháng chấm công nghỉ phép thuộc 2 khoa khác nhau và Yêu cầu chỉnh lại khi xem số ngày nghỉ của nhân viên chỉ hiển thị 1 dòng tên Họ tên nhân viên, ngày nghỉ... Hiện tại đang load lên nhiều dòng như hình dưới
HRM->Lương->Báo cáo->Ngày phép năm (Thông tin như hình dưới)
![image](https://github.com/user-attachments/assets/0b65e8af-8f07-4e08-827e-c137cc1b9b40)

HÌnh khi xem số ngày công và so sánh trong dữ liệu
![image](https://github.com/user-attachments/assets/477dbf89-0bf0-4335-8a4a-b41aa472d763)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Thực hiểm kiểm và chỉnh lỗi._**

- **⏳ Thời gian hoàn thành:** **_2024-11-22_** 

- **🧑‍💻 Thực hiện:** @nqhoa1005 

---

<sup>**📢Lưu ý tiếp nhận:**</sup>
<sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
<sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
<sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
<sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>

**Comment by nqhoa1005** [comment]
✅ HOÀN THÀNH

---
![](https://i.imgur.com/qWFkk0j.png)

---
- ⏯️ anh @tolaptrinh-issue check giúp em

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 HRM.exe v.3.24.1124.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHRMexe%2F32411240-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHRMexe%2F32411240-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHRMexe%2F32411240-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi
Merge pull request #1 from code-dh-hospital-training/main

- 🐛: HRM không lấy sai số ngày nghỉ phép năm
- ☑: https://github.com/dhhiswork/Loi/issues/19
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40web--flow-informational?logo=github)](https://github.com/web-flow) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/HRM.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by hvtuan1987** [comment]
-  ✔️ **Xác nhận HRM đã Fix lỗi trên** 
![image](https://github.com/user-attachments/assets/e61e6cb7-576d-45ef-ad2b-138a36f41f44)
