### ISSUE TITLE
Lỗi - Bảng kê 6556 bệnh ARV không lấy được mã ICD phụ

### ISSUE THREAD

**Issue by le-an-87** [dhhiswork/Loi#21]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **20/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Cái Răng**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_cairang_dsxn_20112024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_cairang_dsxn_20112024`](https://gofile.me/78TQg/GKRJUrXT9)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023016818` - _**MaKB**_: `2411006394` - _**MaBA**_: `N2023003718` _**NgayKCB**_: `20/11/2024` - _**MaPhong**_: `42` - _**MaDV**_: `01` - _**ThangKT**_: `11` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bảng kê 6556 bệnh ARV không lấy được mã ICD phụ đã chỉ định

```
![ảnh](https://github.com/user-attachments/assets/61093019-ae6a-45a3-80f9-45d6c6684a07)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Kiểm tra nguyên nhân dữ liệu có trong current.qtdieutri mà lại hông có trong current.khambenh._**

- **⏳ Thời gian hoàn thành:** **_2024-12-02_** 

- **🧑‍💻 Thực hiện:** @lequocthong29 

---

<sup>**📢Lưu ý tiếp nhận:**</sup>
<sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
<sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
<sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
<sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @le-an-87 
- **📘 Nội dung:** Thực hiện script cập nhật đối với trường hợp này: ![](https://i.imgur.com/TuQlAAn.png) ![](https://i.imgur.com/b7ZlKys.png)

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Kiểm tra nguyên nhân dữ liệu có trong current.qtdieutri mà lại hông có trong current.khambenh.
-  📆 **Thời gian hoàn thành :**  2024-12-02.

**Comment by le-an-87** [comment]
> ### 📢 Thảo luận - trao đổi
> 
>     * **🧑‍💻 Thảo luận:** @le-an-87
> 
>     * **📘 Nội dung:** Thực hiện script cập nhật đối với trường hợp này: ![](https://camo.githubusercontent.com/1cf9107b2bf6ab9ea6277cc1c2d94d512a13f904c7a3ce15127f09046561fb38/68747470733a2f2f692e696d6775722e636f6d2f5475516c41416e2e706e67)

Các trường hợp khác thì xử lý thế nào vậy anh. bv không chỉ bị duy nhất trường hợp này!

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @le-an-87 
- **📘 Nội dung:** Trường hợp này phải đợi Prescription cập nhật chức năng này xong, thì sẽ viết script để cập nhật những trường hợp bị lỗi. Nhờ @le-an-87 lấy dữ liệu cả tháng hoặc nhiều hơn để tiện cho việc viết script để cập nhật lại các trường hợp này nhé.

- **🧑‍💻 Thảo luận:** @lequocthong29 
- **📘 Nội dung:** Khi chỉnh xong lỗi này, viết script để thực hiện cập nhật lại những dữ liệu bị sai này.

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Prescription.exe v.3.24.1202.2 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32412022-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32412022-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32412022-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Fix lỗi bệnh án ARV mất dữ liệu cột current.khambenh.maicdp khi thêm toa thuốc.

- ☑: https://github.com/dhhiswork/Loi/issues/21
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Prescription.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
### ☑️ KẾT QUẢ KIỂM TRA SẢN PHẨM ☑️  
## Lần 1
> ✅  Hình ảnh chứng mình cho việc kiểm tra này:
![ảnh](https://github.com/user-attachments/assets/3fb3e1a2-8c83-43bb-b9a4-8340bfaff566)

**Comment by le-an-87** [comment]
### **HoànThành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
