### ISSUE TITLE
Lỗi - DS xét nghiệm bị double bệnh nhân (BV Cái răng)

### ISSUE THREAD

**Issue by le-an-87** [dhhiswork/Loi#22]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **20/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Cái Răng**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_cairang_dsxn_20112024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_cairang_dsxn_20112024`](https://gofile.me/78TQg/GKRJUrXT9)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023016818` - _**MaKB**_: `2411006394` - _**MaBA**_: `N2023003718` _**NgayKCB**_: `20/11/2024` - _**MaPhong**_: `42` - _**MaDV**_: `01` - _**ThangKT**_: `11` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Danh sách bệnh nhân thực hiện xét nghiệm bị double bệnh nhân.

```
![ảnh](https://github.com/user-attachments/assets/7e1de6d8-daf1-4f4c-a0f1-31d0254228e0)
![ảnh](https://github.com/user-attachments/assets/358bd141-95e0-4142-9d49-a80424b9ae6e)
![ảnh](https://github.com/user-attachments/assets/686b136a-4e49-4b61-84fc-509a6efa170c)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-11-22_** 

- **🧑‍💻 Thực hiện:** @vinh-dh 

---

<sup>**📢Lưu ý tiếp nhận:**</sup>
<sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
<sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
<sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
<sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>

**Comment by vinh-dh** [comment]
✔️ Đã tiếp nhận.
⏳ Thời gian hoàn thành dự kiến: 2024-11-22.

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 DH.Laboratory.exe v.3.24.1121.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FDHLaboratoryexe%2F32411210-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FDHLaboratoryexe%2F32411210-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FDHLaboratoryexe%2F32411210-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Sửa lỗi: Danh sách xét nghiệm bị double bệnh nhân (BV Cái răng).

![image](https://github.com/user-attachments/assets/c5aaea34-a920-4784-a0c6-b7f06b0ea893)

- ☑: https://github.com/dhhiswork/Loi/issues/22
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Laboratory.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
### ❓ TRAO ĐỔI ❓ 
❔ Câu hỏi: xét nghiệm đã thực hiện rồi sao sổ xét nghiệm và sổ xét nghiệm tt14 lại không load lên được vậy anh @vinh-dh 
![ảnh](https://github.com/user-attachments/assets/43a168c5-dcfc-4ec0-b2de-bafd559ecf40)
![ảnh](https://github.com/user-attachments/assets/eb47b9f9-e223-49e9-88c6-d7377cda7573)
***

**Comment by vinh-dh** [comment]
> ### ❓ TRAO ĐỔI ❓
> ❔ Câu hỏi: xét nghiệm đã thực hiện rồi sao sổ xét nghiệm và sổ xét nghiệm tt14 lại không load lên được vậy anh @vinh-dh !

Em lập git báo lỗi nhé!

**Comment by le-an-87** [comment]
này em chỉ hỏi  thôi chứ ghi git làm gì

**Comment by vinh-dh** [comment]
@le-an-87 lỗi thì cứ báo git để anh kiểm tra và fix lỗi. Chứ em hỏi chi nữa?

**Comment by le-an-87** [comment]
không xác định được nên hỏi để biết thôi!

**Comment by vinh-dh** [comment]
Thông tin không cụ thể thì anh cũng không biết được nguyên nhân. Với lại nó không thuộc phạm vi của git này.

**Comment by le-an-87** [comment]
### ☑️ KẾT QUẢ KIỂM TRA SẢN PHẨM ☑️  
## Lần 1
## 
***
> 🟥 Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.
- Diễn giải lỗi:
- Hình ảnh lỗi:
> ✅  Hình ảnh chứng mình cho việc kiểm tra này.
![ảnh](https://github.com/user-attachments/assets/e1157114-c071-453b-aadd-cd2b1dab8fe5)

> 📘 Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***

**Comment by le-an-87** [comment]
### **HoànThành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
