### ISSUE TITLE
Lỗi - Một số lỗi thao tác module Treatment

### ISSUE THREAD

**Issue by le-an-87** [dhhiswork/Loi#25]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **21/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_cairang_dsxn_20112024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024000001` - _**MaKB**_: `2411006395` - _**MaBA**_: `2024000002` _**NgayKCB**_: `21/11/2024` - _**MaDV**_: `05` - _**ThangKT**_: `11` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Tổng hợp một số lỗi module Treatment
- [ ] Chức năng chỉnh đối tượng: không hiển thị được danh sách bệnh viện để chọn bvdk
- [ ] Chức năng chỉnh đối tượng: nhập nơi giới thiệu nhưng không ràng buộc nhập trạng thái chuyển tuyến
- [x] Chọn bác sĩ: không double chuột để chọn bác sĩ được.
- [ ] Quá trình điều trị: khi chỉnh cho phép nhập thêm y lệnh -> khi lưu và đóng lại không in được y lệnh đã nhập và thoát ra vào lại bị mất y lệnh.
- [x] Lỗi cập nhật y lệnh.
- [x] Chức năng C.nhật thẻ CLS không có tác dụng

![ảnh](https://github.com/user-attachments/assets/5fcdc7e1-31fc-4c28-b8bc-00936655ab63)
![ảnh](https://github.com/user-attachments/assets/4ab23c8d-05db-44c6-be0f-527e391dd83b)
![ảnh](https://github.com/user-attachments/assets/1613b528-47dd-497d-b92b-469a9a9faa0f)
![ảnh](https://github.com/user-attachments/assets/686a1b3e-fd6f-4b1c-9c47-7c90dcf9655f)
![ảnh](https://github.com/user-attachments/assets/ee0263ac-2565-4c86-aaf0-31258609b37b)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-11-23_** 

- **🧑‍💻 Thực hiện:** @vuongdh 

---

<sup>**📢Lưu ý tiếp nhận:**</sup>
<sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
<sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
<sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
<sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhật


⏳ Thời gian hoàn thành: 2024-11-26

**Comment by vuongdh** [comment]
Chức năng chỉnh đối tượng: nhập nơi giới thiệu nhưng không ràng buộc nhập trạng thái chuyển tuyến <= này ràng buột sao @le-an-87 . Theo mô tả thì chỉ ràng buột với nơi giới thiệu. Anh chưa hiểu ý em lắm

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @lequocthong29 
- **📘 Nội dung:** Xem hiện Register đang bắt ràng buộc thế nào, mô tả để Treatment thực hiện luôn.

**Comment by vuongdh** [comment]
@lequocthong29 Gửi anh lại cái mô tả hén. Vì theo mô tả 4750. Chỉ ràng buộc nhiêu đây
![image](https://github.com/user-attachments/assets/6010c122-755a-4974-90c7-b2ce74c1760b)

**Comment by lequocthong29** [comment]
@vuongdh E đang bắt theo mô tả này a
![image](https://github.com/user-attachments/assets/ccfed7eb-0675-4962-bceb-ba4b876de49d)

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Treatment.exe v.4.24.1126.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42411260-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42411260-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42411260-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Lỗi - Một số lỗi thao tác module Treatment #25

- Chức năng chỉnh đối tượng: không hiển thị được danh sách bệnh viện để chọn bvdk

![](https://i.imgur.com/jDUiBPO.gif)

- Chức năng chỉnh đối tượng: nhập nơi giới thiệu nhưng không ràng buộc nhập trạng thái chuyển tuyến

--> Khi tham số tuyenbv = 3 (tuyến tỉnh) và mã nơi giới thiệu khác rỗng --> bắt buột nhập: trạng thái chuyển tuyến

- Chọn bác sĩ: không double chuột để chọn bác sĩ được.

![](https://i.imgur.com/GkhRZs0.gif)

- Quá trình điều trị: khi chỉnh cho phép nhập thêm y lệnh -> khi lưu và đóng lại không in được y lệnh đã nhập và thoát ra vào lại bị mất y lệnh.

- Lỗi cập nhật y lệnh.

![](https://i.imgur.com/Nnwv6P4.gif)

- Chức năng C.nhật thẻ CLS không có tác dụng

![](https://i.imgur.com/TCIhGk4.gif)

- ☑: https://github.com/dhhiswork/Loi/issues/25
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Treatment.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
### ☑️ KẾT QUẢ KIỂM TRA SẢN PHẨM ☑️  
## Lần 1

- [ ] Chức năng chỉnh đối tượng: không hiển thị được danh sách bệnh viện để chọn bvdk
![46uLUlZbY0](https://github.com/user-attachments/assets/50c4cc6c-e9de-4adc-9339-e2ca160e54d9)
- [ ] Chức năng chỉnh đối tượng: nhập nơi giới thiệu nhưng không ràng buộc nhập trạng thái chuyển tuyến
![Treatment_8YBXaidTrh](https://github.com/user-attachments/assets/5a56efaa-ca71-433b-9c4b-cb4ee2e57ecd)
- [x] Chọn bác sĩ: không double chuột để chọn bác sĩ được.
![Treatment_QNX64lPWo8](https://github.com/user-attachments/assets/e468b1ef-b8d8-40cf-9e86-c907b6c6fb4c)
- [ ] Quá trình điều trị: khi chỉnh cho phép nhập thêm y lệnh -> khi lưu và đóng lại không in được y lệnh đã nhập và thoát ra vào lại bị mất y lệnh.
![Treatment_Q01fNk7qxq](https://github.com/user-attachments/assets/9ca7d093-ef12-4519-9b18-fde476d6fa08)
- [x] Lỗi cập nhật y lệnh.
![ảnh](https://github.com/user-attachments/assets/2bbe21ca-8ef3-42e2-b98f-e3ff4a11dbab)
- [x] Chức năng C.nhật thẻ CLS không có tác dụng
![ảnh](https://github.com/user-attachments/assets/324e94c4-eca1-40b4-9d9e-ee9345eba095)
![ảnh](https://github.com/user-attachments/assets/316fa6bd-f632-44fe-b332-e4eb8bce7d54)

***

**Comment by le-an-87** [comment]
### 🚨 CHƯA HOÀN THÀNH 🚨 
✅  Hoàn thành kiểm tra
🚨 Phần mềm chưa đáp ứng đúng yêu cầu.
***
![ảnh](https://github.com/user-attachments/assets/b5f5472a-b76d-4223-a97e-1b45c312d25d)
1. Chức năng chỉnh đối tượng: Lỗi danh mục bệnh viện load luôn các bệnh viện đã xóa
2. Chức năng chỉnh đối tượng: chưa ràng buộc nhập trạng thái chuyển tuyến -> xml.madoituong = 9
3. QT điều trị: chức năng chỉnh không cập nhật được y lệnh -> nếu không cập nhật thì khóa không cho nhập

**Comment by vuongdh** [comment]
> 2. Chức năng chỉnh đối tượng: chưa ràng buộc nhập trạng thái chuyển tuyến -> xml.madoituong = 9

TEST THEO MÔ TẢ: 
![image](https://github.com/user-attachments/assets/44af6872-de01-4eb4-91ac-86a699abcb15)

--> Cách ghi nhận dữ liệu có đúng với mô tả chưa, sai thì sai như thế nào? đề nghị ghi rõ để nhóm code dễ thực hiện fix code

**Comment by vuongdh** [comment]
> 2. Chức năng chỉnh đối tượng: chưa ràng buộc nhập trạng thái chuyển tuyến -> xml.madoituong = 9

--> Theo mô tả: chỉ bắt buộc nhập 'trạng thái chuyển tuyến' khi tham số tuyenbv = 3. Em coi lại chổ này

**Comment by vuongdh** [comment]
> > 2. Chức năng chỉnh đối tượng: chưa ràng buộc nhập trạng thái chuyển tuyến -> xml.madoituong = 9
> 
> --> Theo mô tả: chỉ bắt buộc nhập 'trạng thái chuyển tuyến' khi tham số tuyenbv = 3 và mã nơi giới thiếu khác rỗng. Em coi lại chổ này

**Comment by vuongdh** [comment]
> 1. Chức năng chỉnh đối tượng: Lỗi danh mục bệnh viện load luôn các bệnh viện đã xóa
> 2. Chức năng chỉnh đối tượng: chưa ràng buộc nhập trạng thái chuyển tuyến -> xml.madoituong = 9
> 3. QT điều trị: chức năng chỉnh không cập nhật được y lệnh -> nếu không cập nhật thì khóa không cho nhập

✔️ Đã tiếp nhật
⏳ Thời gian hoàn thành: 2024-11-29

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Treatment.exe v.4.24.1128.1 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42411281-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42411281-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42411281-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Lỗi - Một số lỗi thao tác module Treatment #25

- Fix lỗi chỉnh đổi tượng --> load bệnh viện đã xóa

- Fix lỗi from quá trình điều trị: chưa nhấn cập nhật vẫn nhập được y lệnh --> in có y lệnh, nhưng khi tắt form mở lại thì y lệnh bị mất.

![](https://i.imgur.com/bjPMrNc.gif)

- ☑: https://github.com/dhhiswork/Loi/issues/25
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Treatment.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
### ☑️ KẾT QUẢ KIỂM TRA SẢN PHẨM ☑️  
## Lần 2
## 
***
> 🟥 Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.
- Diễn giải lỗi:
- Hình ảnh lỗi:
> ✅  Hình ảnh chứng mình cho việc kiểm tra này:
1. Chức năng chỉnh đối tượng: Lỗi danh mục bệnh viện load luôn các bệnh viện đã xóa
![ảnh](https://github.com/user-attachments/assets/3ab3f867-b34d-4cfe-bef7-7e5090dc3ac3)
2.  Chức năng chỉnh đối tượng: chưa ràng buộc nhập trạng thái chuyển tuyến -> xml.madoituong = 9
![ảnh](https://github.com/user-attachments/assets/566a7346-3c40-4e2b-9be2-8c8086f7c3d3)
![ảnh](https://github.com/user-attachments/assets/909b5e69-810b-4f35-9de0-b228a111259f)
3. QT điều trị: chức năng chỉnh không cập nhật được y lệnh -> nếu không cập nhật thì khóa không cho nhập
![ảnh](https://github.com/user-attachments/assets/afd0e951-d6a8-4b85-af0d-d1d0a907a457)
![ảnh](https://github.com/user-attachments/assets/85f063be-9505-46df-ba5a-f63c49018a0a)

> 📘 Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***

**Comment by le-an-87** [comment]
### **HoànThành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
