### ISSUE TITLE
Lỗi - Admin load sai danh sách đối tượng KHÔNG BHYT

### ISSUE THREAD

**Issue by lqbinh1987** [dhhiswork/Loi#27]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **21/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `ALL`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **ALL**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_thanhtri_full`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/Z7jfKbk98)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024010639` - _**MaKB**_: `2409001614` - _**MaBA**_: `MaBA` _**NgayKCB**_: `21/11/2024` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `09` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

BN là đối tượng BHYT, nhưng không có chi phí liên quan đến BHYT, khi chọn là ds **Không BHYT** thì load được => đúng.
Nhưng khi chọn ds là **BHYT** thì phần mềm vẫn load lên được BN đó.
![image](https://github.com/user-attachments/assets/fb9443ae-5ecd-4f00-ae69-616d4b075ed6)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** 
  - **_Kiểm thử và xác nhận lỗi có xảy ra hay không._**
  - **_Nếu có lỗi xảy ra, thực hiện tái lại trường hợp với bệnh nhân mới, trên dữ liệu mới chi có 1 bệnh nhân._**

- **⏳ Thời gian hoàn thành:** **_2024-11-22_** 

- **🧑‍💻 Thực hiện:** @nqhoa1005 

---

<sup>**📢Lưu ý tiếp nhận:**</sup>
<sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
<sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
<sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
<sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>

**Comment by nqhoa1005** [comment]
- ✔️ **Tiếp nhận công việc** 
- 📆 Thời gian hoàn thành dự kiến : ** 2024-11-22**

**Comment by nqhoa1005** [comment]
- [x]  Test trên dữ liệu cung cấp tại Git này
👉 tình trạng lỗi có xảy ra

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
> _**MaBN**_: `2023003896` -_**MaKB**_: `2408012833` - _**MaBA**_: `2024007028` - _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `NH1` - _**MaDV**_: `18` - _**ThangKT**_: `09` - _**NamKT**_: `2024`
- BN không có chi phí BHYT
![](https://i.imgur.com/YUXr996.png)
![](https://i.imgur.com/Reaaatp.png)
![](https://i.imgur.com/wcyX4Cj.png)

khi lọc lại danh sách BHYT vẫn thể hiện
![](https://i.imgur.com/iDWQHnj.png)

---

- [x] Test trên dữ liệu 1 bệnh nhân
✳️ Thông tin dữ liệu test
- ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_thanhtri_loc4750` 
- ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434` 
- ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/DQy7BoiN5) 

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
> _**MaBN**_: `2012013153` -_**MaKB**_: `2409001616` - _**MaBA**_: `MaBA` - _**NgayKCB**_: `25/11/2024` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `09` - _**NamKT**_: `2024`

![](https://i.imgur.com/pEy1MWT.png)

👉 lọc theo BHYT
![](https://i.imgur.com/WObeYIp.png)

👉 Lọc theo Không BHYT
![](https://i.imgur.com/377eENT.png)

❌ Kết quả thử lại trên ca mới BN chỉ thể hiện bên danh sách BHYT không có khi chọn Không BHYT > Sai

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @nqhoa1005 
- **📘 Nội dung:** Kiểm thử thêm trường hợp này, những trường hợp bị lỗi, dùng chức năng Đối soát hồ sơ 130 và 4210 xong, xem còn bị tình trạng này nữa hông. Mã bệnh án `2024007028` bị lỗi là do ghi nhận dữ liệu bị sai nên chạy là hết.

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by nqhoa1005** [comment]
✳️ Thông tin dữ liệu :
- ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BỆNH VIỆN ĐA KHOA SA ĐÉC**
- ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_tpsadec_2811` 
- ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434` 
- ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/HoOhaLjqd) 

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
> _**MaBN**_: `2019063452` -_**MaKB**_: `2411000003` - _**MaBA**_: `MaBA` - _**NgayKCB**_: `28/11/2024` - _**MaPhong**_: `11` - _**MaDV**_: `PK` - _**ThangKT**_: `11` - _**NamKT**_: `2024`
-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
> _**MaBN**_: `2021000698` -_**MaKB**_: `2411000002` - _**MaBA**_: `MaBA` - _**NgayKCB**_: `28/11/2024` - _**MaPhong**_: `11` - _**MaDV**_: `PK` - _**ThangKT**_: `11` - _**NamKT**_: `2024`

---
Do dữ liệu có nhiều lỗi do sử dụng bản cũ nên em đã phối hợp với anh @lqbinh1987 test lại trên dữ khác và nhận bệnh mới.

👉 Kết quả những hồ sơ không có chi phí BHYT đều load khi lọc theo BHYT không có tình trạng load cả 2 bên như ca báo tại Git này.
![](https://i.imgur.com/ruUlcF7.png)

👉 Do không có chi phí BHYT nên khi xuất 4210 và chứng năng Đối soát hồ sơ cũng không thấy hồ sơ đó để chạy được tools
![](https://i.imgur.com/Mf8JA9n.png)

anh @lqbinh1987 anh @tolaptrinh-issue

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @nqhoa1005 
- **📘 Nội dung:** Cái quan trọng mình cần biết là phần mềm còn lỗi hông? Nói dong, nói dài, hông có kết lại vấn đề.

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by nqhoa1005** [comment]
❌ Chốt vẫn còn lỗi không có có chi phí BHYT vẫn load lên khi chọn BHYT
![image](https://github.com/user-attachments/assets/ea69c8a8-f542-4975-bbcf-3ae517827eba)
![image](https://github.com/user-attachments/assets/65452240-6489-44f5-8bfd-b31d9de0e993)
![image](https://github.com/user-attachments/assets/16f1ce4f-278a-480a-b941-515aa3411400)

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 HospitalPrinter.exe v.3.24.1128.1 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalPrinterexe%2F32411281-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalPrinterexe%2F32411281-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalPrinterexe%2F32411281-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: - 🐛: Lỗi - Admin load sai danh sách đối tượng KHÔNG BHYT

- 🐛: Chỉnh lỗi ghi nhận sai giá trị XML01.T_TONGCHI_BH khi tạo XML4750 (những trường hợp có PHAM_VI=2). Những trường hợp đã ghi nhận sai phải dùng Chức năng đối soát, nếu không có hồ sơ đối soát phải dùng module mới để in lại phiếu 01.

- ![](https://i.imgur.com/KIRuxe5.gif)

- ☑: https://github.com/dhhiswork/Loi/issues/27
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/HospitalPrinter.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.1128.2 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalAdminexe%2F32411282-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalAdminexe%2F32411282-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalAdminexe%2F32411282-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: - 🐛: Lỗi - Admin load sai danh sách đối tượng KHÔNG BHYT

- 🐛: Chỉnh lỗi ghi nhận sai giá trị XML01.T_TONGCHI_BH khi tạo XML4750 (những trường hợp có PHAM_VI=2). Những trường hợp đã ghi nhận sai phải dùng Chức năng đối soát, nếu không có hồ sơ đối soát phải dùng module mới để in lại phiếu 01.

- ![](https://i.imgur.com/KIRuxe5.gif)

- ☑: https://github.com/dhhiswork/Loi/issues/27
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/HospitalAdmin.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Reports.exe v.3.24.1128.2 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FReportsexe%2F32411282-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FReportsexe%2F32411282-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FReportsexe%2F32411282-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Lỗi - Admin load sai danh sách đối tượng KHÔNG BHYT

- 🐛: Chỉnh lỗi ghi nhận sai giá trị XML01.T_TONGCHI_BH khi tạo XML4750 (những trường hợp có PHAM_VI=2). Những trường hợp đã ghi nhận sai phải dùng Chức năng đối soát, nếu không có hồ sơ đối soát phải dùng module mới để in lại phiếu 01.

- ![](https://i.imgur.com/KIRuxe5.gif)

- ☑: https://github.com/dhhiswork/Loi/issues/27
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Reports.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Prescription.exe v.3.24.1128.2 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32411282-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32411282-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32411282-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: - 🐛: Lỗi - Admin load sai danh sách đối tượng KHÔNG BHYT

- 🐛: Chỉnh lỗi ghi nhận sai giá trị XML01.T_TONGCHI_BH khi tạo XML4750 (những trường hợp có PHAM_VI=2). Những trường hợp đã ghi nhận sai phải dùng Chức năng đối soát, nếu không có hồ sơ đối soát phải dùng module mới để in lại phiếu 01.

- ![](https://i.imgur.com/KIRuxe5.gif)

- ☑: https://github.com/dhhiswork/Loi/issues/27
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Prescription.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Thực hiện kiểm thử lại trường hợp lỗi này._**

- **⏳ Thời gian hoàn thành:** **_2024-11-29_** 

- **🧑‍💻 Thực hiện:** @nqhoa1005 

---

<sup>**📢Lưu ý tiếp nhận:**</sup>
<sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
<sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
<sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
<sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by nqhoa1005** [comment]
✅ HOÀN THÀNH

---

✔️  Tiến hành test lại trên ca mới đã load đúng danh sách Không BHYT đối với các hồ sơ không có chi phí BHYT

![image](https://github.com/user-attachments/assets/22465ef9-b6d8-4b21-ab3f-c2b81e388045)
![image](https://github.com/user-attachments/assets/ea1a410f-412b-451a-8eed-b658bcc6bb90)
---
❗❗ **TRAO ĐỔI** ❗❗
👉 Những ca cũ em đã thực hiện test vẫn còn load bên danh sách BHYT _(em đã thử mở khoá in lại thì mới load lại đúng)_
anh @tolaptrinh-issue các ca cũ có phương pháp nào xử lý hay hướng dẫn khách hàng mở khoá in lại để load đúng anh vì những hồ sơ không có chi phí BHYT không có tên trên 4210 để chạy tool

![image](https://github.com/user-attachments/assets/ae530db7-2868-4159-b885-701a1378d0f8)

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @nqhoa1005 
- **📘 Nội dung:** Xem nội dung cập nhật, kiểm thử xem đã đúng nội dung cập nhật chưa ![](https://i.imgur.com/bU721cb.png)

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by nqhoa1005** [comment]
❗❗ **TRAO ĐỔI** ❗❗
✔️ anh @tolaptrinh-issue đã đúng nội dung cập nhật

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @lqbinh1987 
- **📘 Nội dung:** Công việc đã hoàn thành, kiểm tra lại sản phẩm.

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by lqbinh1987** [comment]
🐛  Đã fix lỗi:
Đã fix lỗi: Bằng cách lấy module mới in phiếu 01 lại.
![image](https://github.com/user-attachments/assets/f522b0f8-5556-4e41-a5d9-90d44ee6686f)
![image](https://github.com/user-attachments/assets/8c5be3a8-923a-4869-9f00-bb9563cc9626)
![image](https://github.com/user-attachments/assets/6a9e4d20-e11d-4156-b39d-508e2736c1d0)
