### ISSUE TITLE
Lỗi - BV QDY CT: Printer in không lấy thuốc không hiện thông báo in phiếu, trạng thái dain có lúc = 2 (không hiện thông báo in phiếu), có lúc = 3 (có hiện thông báo có in phiếu không bấm bỏ qua), ...

### ISSUE THREAD

**Issue by chauthanhtra** [dhhiswork/Loi#33]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **7/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92092`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV QDY CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_qdy_ct_mau25_khonglaythuoc_29102024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/tKRz5gE3c)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024011791` - _**MaKB**_: `2410000001` - _**MaBA**_: `MaBA` _**NgayKCB**_: `7/11/2024` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `10` - _**NamKT**_: `2024`
   > _**MaBN**_: `2024011794` - _**MaKB**_: `2410000004` - _**MaBA**_: `MaBA` _**NgayKCB**_: `8/11/2024` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `10` - _**NamKT**_: `2024`
   > _**MaBN**_: `2024011795` - _**MaKB**_: `2410000005` - _**MaBA**_: `MaBA` _**NgayKCB**_: `8/11/2024` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `10` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `01` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

[Ghi lại] https://github.com/dh-his/Ghi_Nhan_Loi/issues/43

Printer 07/11/2024 hoặc cũ hơn
Khi in bệnh nhân Không lấy thuốc thì có 3 trường hợp:
1. Bấm Không lấy thuốc thì phần mềm không hiện thông báo hỏi chọn máy in có muốn in hay không, bấm Không lấy thuốc rồi là mất -> ghi nhận trạng thái khambenh.dain = 2
2. Bấm Không lấy thuốc thì phần mềm hiện thông báo hỏi chọn máy in có muốn in hay không, chọn Đóng không in phiếu -> ghi nhận trạng thái khambenh.dain = 3
3. Bấm Không lấy thuốc thì phần mềm hiện thông báo hỏi chọn máy in có muốn in hay không, chọn Đồng ý in phiếu -> ghi nhận trạng thái khambenh.dain = 2 , đồng thời psdangky.dain =1 và các thông tin khác

=> Đề nghị code kiểm tra thống nhất lại cách ghi nhận trạng thái và có mô tả các trường họp này nếu cần thiết

- Clip trường hợp 1 và 2
https://gofile.me/78TQg/nl2tu1kEd

https://youtu.be/d3yyVv0C6JI

- Trường họp 3
![](https://i.imgur.com/inNl6wZ.png)
![](https://i.imgur.com/tRJ4fkK.png)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận và Thực hiện công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-11-27_** 

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @chauthanhtra 
- **📘 Nội dung:** Nhờ thông tin lại rõ hơn các trường hợp lỗi, và thông tin lỗi kèm theo.

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by chauthanhtra** [comment]
- Khi bấm Không lấy thuốc trên Printer thì có mấy trường hợp xảy ra:

1. Phần mềm không hiện thông tin gì hết bấm Không lấy thuốc là xong không có in phiếu hay cho chọn máy in gì hết, bấm Không lấy thuốc là phần mềm im luôn -> trạng thái dain = 2
2. Phần mềm hiện form hỏi chọn máy in và có đồng ý in phiếu hay không
  2.1 Nếu đồng ý in phiếu thì -> trạng thái dain = 2
  2.2 Nếu bỏ qua không in phiếu thì -> trạng thái dain = 3

- Mô tả trường khambenh.dain
![](https://i.imgur.com/gtET5fL.png)

=> Trạng thái dain không chính xác với mô tả. Lúc in được bảng kê lúc không. Không xác định được cái nào mới đúng
Ví dụ: Bệnh nhân có thuốc và CLS . Bấm không lấy thuốc thì trường hợp nào để người dùng biết là bệnh nhân đó được thanh toán CLS, trường hợp nào bỏ luôn không thanh toán CLS luôn. Hiện tại chung không xác định được

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @chauthanhtra 
- **📘 Nội dung:** Trường hợp nhấn Không lấy thuốc mà in phiếu 01, thì sẽ báo cáo, còn trường hợp nhấn mà không in phiếu 01 thì không báo cáo. Nếu lỗi thì cụ thể bệnh nhân nào, lỗi nào, nhờ @chauthanhtra mô tả rõ hơn giúp Tổ lập trình dễ dàng kiểm và chỉnh lỗi.

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by chauthanhtra** [comment]
- Bệnh nhân không in được bảng kê
   > _**MaBN**_: `2024011791` - _**MaKB**_: `2410000001` - _**MaBA**_: `MaBA` _**NgayKCB**_: `7/11/2024` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `10` - _**NamKT**_: `2024`

***
- Bệnh nhân in được bảng kê
   > _**MaBN**_: `2024011795` - _**MaKB**_: `2410000005` - _**MaBA**_: `MaBA` _**NgayKCB**_: `8/11/2024` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `10` - _**NamKT**_: `2024`

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @chauthanhtra 
- **📘 Nội dung:** Trường hợp 2410000001 không in phiếu 01 là do chọn ngày tái khám (khám hôm nay, nhưng xác định ngày kết thúc hồ sơ là ngày khác, giống như hẹn ngày thanh toán) nên trường hợp này đúng ngày đó mới in phiếu 01. Nếu Hủy trạng thái này sẽ in phiếu 01 khi nhấn không lấy thuốc. ![](https://i.imgur.com/aHkSCyB.png)

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @chauthanhtra 
- **📘 Nội dung:** Việc kiểm báo cáo thì có in phiếu 01 thì có lên báo cáo 4210, ngược lại nếu hông in phiếu 01 thì không lên báo cáo. Nhờ kiểm thử lại các trường hợp trên xem còn vướng mắc gì nữa hông. Với chức năng hiện tại, chưa thấy phải chỉnh phần mềm gì thêm nhé.

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by le-an-87** [comment]
### ❓ TRAO ĐỔI ❓ 
❔ Câu hỏi: alo @chauthanhtra 
Bệnh nhân chọn in không lấy thuốc hoặc in không ký tên thì có phân biệt được bệnh đó có in ra bảng kê hay không in không?
-> nếu không có thì hỗ trợ thêm để khách hàng tự kiểm tra được.
Làm rõ các vấn đề này luôn nhé: cái nào có thanh toán cls và cái nào có thanh toán thuốc

  | Không lấy thuốc | | Không ký tên | |
-- | -- | -- | -- | --
**Thanh toán** | **CLS** | **Thuốc** | **CLS** | **Thuốc**
**In bảng kê** | _Có/Không_ | _Có/Không_ | _Có/Không_ | _Có/Không_
**Không in Bảng kê** | _Có/Không_ | _Có/Không_ | _Có/Không_ | _Có/Không_

**Comment by chauthanhtra** [comment]
anh @le-an-87 
  | Không lấy thuốc | | Không ký tên | |
-- | -- | -- | -- | --
**Thanh toán** | **CLS** | **Thuốc** | **CLS** | **Thuốc**
**In bảng kê** | _Có_ | _Không_ | _Có_ | _Không_
**Không in Bảng kê** | _Không_ | _Không_ | _Không_ | _Không_

![](https://i.imgur.com/6pN3zhU.png)
![](https://i.imgur.com/gkRhCEM.png)

- In Không lấy thuốc và in Không ký tên thì không lên Admin, Reports XML130 mặc dù có ghi nhận XML130 trong dữ liệu  -> Lỗi
![](https://i.imgur.com/Tch4BhC.png)
![](https://i.imgur.com/tsCmH59.png)
![](https://i.imgur.com/4Vmh16L.png)

> Bệnh nhân chọn in không lấy thuốc hoặc in không ký tên thì có phân biệt được bệnh đó có in ra bảng kê hay không in không? 
- Có thể phân biệt được dựa vào màu nhưng chỉ biết có in phiếu hay không thôi
![](https://i.imgur.com/vWFW0EG.png)
![](https://i.imgur.com/xKtgRZL.png)

- Hiệu tại chưa phân biệt được bệnh nhân nào là in không ký tên, bệnh nhân nào là in không lấy thuốc
![](https://i.imgur.com/x7xmnAg.png)

- In bệnh nhân không ký tên thì sẽ không có thuốc luôn -> Lỗi
![](https://i.imgur.com/0pUJqE3.png)

Anh @tolaptrinh-issue 
> 📘 Nội dung: Trường hợp 2410000001 không in phiếu 01 là do chọn ngày tái khám (khám hôm nay, nhưng xác định ngày kết thúc hồ sơ là ngày khác, giống như hẹn ngày thanh toán) nên trường hợp này đúng ngày đó mới in phiếu 01. Nếu Hủy trạng thái này sẽ in phiếu 01 khi nhấn không lấy thuốc. 
- Lỗi này là do Prescription khi chỉnh toa là sẽ ghi nhận psdangky.taikham = 1 -> cài này em sẽ báo lỗi git khác

**Comment by le-an-87** [comment]
### ❓ TRAO ĐỔI ❓ 
assig: @tolaptrinh-issue 
❔ Câu hỏi: Kiểm tra lại giùm trường hợp này với nhe anh!
  | Không lấy thuốc | | Không ký tên | |
-- | -- | -- | -- | --
**Thanh toán** | **CLS** | **Thuốc** | **CLS** | **Thuốc**
**In bảng kê** | _Có_ | _Không_ | _Có_ | _Không_
**Không in Bảng kê** | _Không_ | _Không_ | _Không_ | _Không_

1. Nếu chức năng in không lấy thuốc và không ký tên giống nhau thì bỏ giúp 1 chức năng.
2. Đề xuất bổ sung nhật ký ghi nhận bệnh có in bảng kê hay không nhe.

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @le-an-87 
- **📘 Nội dung:** Giải thích trường hợp 1. Đây là hai chức năng khác nhau, chứ không phải cùng chức năng nhé. Phần 2. ghi nhật ký sẽ bổ sung thêm các thao tác này nhé.

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận và Thực hiện công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Ghi nhận ký đối với trường hợp Không lấy thuốc, In bệnh nhân không ký tên._**

- **⏳ Thời gian hoàn thành:** **_2024-12-06_** 

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by le-an-87** [comment]
### ❓ TRAO ĐỔI ❓ 
Vậy nhờ anh @tolaptrinh-issue giải thích 2 chức năng đó để tổ em hiểu hơn về chức năng nhe anh
1. mục đích của 2 chức năng đó?
2. tại sao báo cáo lại giống nhau
![ảnh](https://github.com/user-attachments/assets/c839025e-65bc-4cf7-964d-7ba9279d100c)

***

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @le-an-87 
- **📘 Nội dung:** Về mặt báo cáo thì nguyên tắc phải giống nhau. Còn in không ký tên sẽ ghi nhận lại thẻ BHYT ở trạng thái không ký tên, để chỗ nhận bệnh xử lý khi nhận bệnh gặp những thẻ đã ghi nhận chưa ký tên sẽ thông báo là thẻ này có ghi nhận chưa ký tên vào ngày đó, và hỏi người dùng có tiếp tục thao tác nhận bệnh tiếp hay không.

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by le-an-87** [comment]
### ❓ TRAO ĐỔI ❓ 
ok cám ơn anh @tolaptrinh-issue.
@chauthanhtra , @minhduc2it ghi nhận để hướng dẫn khách hàng sử dụng chức năng nhé!
***

**Comment by chauthanhtra** [comment]
> ### ✔️ Tiếp nhận và Thực hiện công việc[HD.05]
> 
>     * **📘 Mô tả thực hiện:** **_Ghi nhận ký đối với trường hợp Không lấy thuốc, In bệnh nhân không ký tên._**
> 
>     * **⏳ Thời gian hoàn thành:** **_2024-12-06_**
> 
> 
> 📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue

anh @tolaptrinh-issue 
Có phần mềm "Ghi nhận ký đối với trường hợp Không lấy thuốc, In bệnh nhân không ký tên" chưa vậy anh?

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @chauthanhtra 
- **📘 Nội dung:** Kiểm lại, hiện chưa có chức năng này. Sẽ bổ sung thêm.

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @chauthanhtra 
- **📘 Nội dung:** Hiện đã ghi nhật ký rồi. Trong chức năng này: ![](https://i.imgur.com/1kOjyuu.png)

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by chauthanhtra** [comment]
### ✔️ **ĐÃ TIẾP NHẬN**
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '13/12/2024'.
***

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm HospitalPrinter.exe v.3.24.1211.0
***

### 🆘 **Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.**

- Diễn giải lỗi:
  - Printer không ghi nhận nhật ký in không lấy thuốc và in không ký tên vào chức năng Nhật ký in toa như hướng dẫn của code mà ghi nhật ký vào Nhật ký thao tác -> Đề xuất ghi nhật ký In không lấy thuốc và In không ký tên vào Nhật ký in toa
  - Nhật ký thao tác ghi nhận nhật ký in không lấy thuốc và in không ký tên nhưng nội dung Tác vụ ghi Không lấy thuốc (không phân biệt được 2 loại in phiếu khác nhau) ->Đề xuất tác vụ ghi rõ để phân biệt
  -> Đề xuất ghi nhật ký tác vụ In không lấy thuốc không in bảng kê và In bệnh nhân không ký tên không in bảng kê để phân biệt với trường hợp có in bảng kê
- Hình ảnh lỗi:
![](https://i.imgur.com/l024M3l.gif)


***
Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### ❎ **CHƯA HOÀN THÀNH**
- Hoàn thành kiểm tra
- Phần mềm chưa đáp ứng đúng yêu cầu.
- Yêu cầu Tổ coder kiểm tra lại.

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 HospitalPrinter.exe v.3.24.1213.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalPrinterexe%2F32412130-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalPrinterexe%2F32412130-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalPrinterexe%2F32412130-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Lỗi - BV QDY CT: Printer in không lấy thuốc không hiện thông báo in phiếu, trạng thái dain có lúc = 2 (không hiện thông báo in phiếu), có lúc = 3 (có hiện thông báo có in phiếu không bấm bỏ qua), ... ·

- 🐛: Bổ sung chức năng ghi nhật ký đối Khi in BN không ký tên, Không lấy thuốc không in phiếu ![](https://i.imgur.com/aP7DfkT.png)

- ☑: https://github.com/dhhiswork/Loi/issues/33#issuecomment-2539577215
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/HospitalPrinter.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm HospitalPrinter.exe v.3.24.1217.0
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Phần mềm đã ghi nhận nhật ký in không lấy thuốc và in không ký tên có in phiếu và không in phiếu

- Hình ảnh: 
![](https://i.imgur.com/gdsKMZ2.gif)
![](https://i.imgur.com/VEOO2Ol.png)

**Comment by chauthanhtra** [comment]
### ✅ **HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
