### ISSUE TITLE
Lỗi - lệch tiền thuốc giữa mẫu 79 và bảng kê 6556 (BV Phụ sản)

### ISSUE THREAD

**Issue by le-an-87** [dhhiswork/Loi#39]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **25/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phụ Sản**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phusan_80_6556_25112024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_phusan_80_6556_25112024`](https://gofile.me/78TQg/tJbyz0zRA)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024095385` - _**MaKB**_: `2411011454` - _**MaBA**_: `020376` _**NgayKCB**_: `24/11/2024 2:30:00 CH` - _**MaPhong**_: `K_NHI` - _**MaDV**_: `17` - _**ThangKT**_: `11` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `14` - _**MaHH**_: `CE214` - _**SoHD**_: `NI7.X24.1124.134318` - _**NgayHD**_: `24/11/2024` - _**ThangKT**_: `11` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Lệch tiền thuốc giữa mẫu xml130 và mẫu 6556
(tổng theo form số lượng thực xuất cũng = 13 nhưng bảng kê hiển thị số lượng = 14)
```
![ảnh](https://github.com/user-attachments/assets/e8b36633-010e-493f-9b3d-98666595c1f8)
![ảnh](https://github.com/user-attachments/assets/44deb213-275a-4995-ae4c-ec833889406b)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-11-27_** 

- **🧑‍💻 Thực hiện:** @vinh-dh 

---

<sup>**📢Lưu ý tiếp nhận:**</sup>
<sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
<sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
<sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
<sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by vinh-dh** [comment]
✔️ Đã tiếp nhận.
⏳ Thời gian hoàn thành dự kiến: 2024-11-27.

**Comment by vinh-dh** [comment]
✅ XÁC ĐỊNH ĐƯỢC NGUYÊN NHÂN ✅
----------------------------------------------
Số hóa đơn: `NI7.X24.1124.134318` của mặt hàng `VE68`
- Tại table chungtu đã bị đánh dấu xóa.
![image](https://github.com/user-attachments/assets/0256e708-0bff-41db-8253-180b96373ee2)

- Tại table pshdxn thì không.
![image](https://github.com/user-attachments/assets/db7d11eb-4409-48a5-9f4b-cead440c77ab)

Chuyển @vuongdh kiểm tra nhé!

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhật

⏳ Thời gian hoàn thành: 2024-12-03

@vinh-dh hỗ trợ phục hồi một toa cho khớp dữ liệu dùm

**Comment by vinh-dh** [comment]
Script fix trường hợp trên:
![image](https://github.com/user-attachments/assets/b1d3f070-aa72-4d8b-b503-90941fe9a182)

**Comment by le-an-87** [comment]
### ☑️ KẾT QUẢ KIỂM TRA SẢN PHẨM ☑️  
## Lần 1
> ✅  Hình ảnh chứng mình cho việc kiểm tra này:
![ảnh](https://github.com/user-attachments/assets/e7f0ef98-27cf-478f-bcac-d11770699470)
![ảnh](https://github.com/user-attachments/assets/675b2971-6a01-42cc-a019-b459b14a3b6c)

> 📘 Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***

**Comment by le-an-87** [comment]
### **HoànThành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Treatment.exe v.4.24.1203.3 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42412033-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42412033-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42412033-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Lỗi - lệch tiền thuốc giữa mẫu 79 và bảng kê 6556 (BV Phụ sản)

- Cập nhật:

![](https://i.imgur.com/6KwV3g1.gif)

- ☑: https://github.com/dhhiswork/Loi/issues/39
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Treatment.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>
