### ISSUE TITLE
Lỗi - XML5_4750 load thiếu thông tin thủ thuật (BV Quảng ngãi)

### ISSUE THREAD

**Issue by le-an-87** [dhhiswork/Loi#41]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **31/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_quangngai_31102024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2020008159` - _**MaKB**_: `2410005595` - _**MaBA**_: `2024001746` _**NgayKCB**_: `28/10/2024 4:30:00 CH` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `16` - _**ThangKT**_: `10` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Đã ghi nhận issuse https://github.com/dh-his/Ghi_Nhan_Loi/issues/31
```
Bệnh nhân ngày 22/10/2024 có chỉ định 2 cls DI122 và SA03 đã lập phiếu thủ thuật
-> XML5 chỉ load được thông tin 1 phiếu thủ thuật.

```
![ảnh](https://github.com/user-attachments/assets/15c77408-9384-4c7b-a87c-19b71bb455c3)
![ảnh](https://github.com/user-attachments/assets/f4cd20b9-c583-4dc2-a026-5d24b0d81262)
![ảnh](https://github.com/user-attachments/assets/b924a85c-1728-4fd2-aa17-da4944282113)

**Comment by le-an-87** [comment]
![ảnh](https://github.com/user-attachments/assets/e2b8c6a8-205c-4ab3-9b78-21aacb7fd60c)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận và Thực hiện công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-11-28_** 

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.1126.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalAdminexe%2F32411260-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalAdminexe%2F32411260-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalAdminexe%2F32411260-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Lỗi - XML5_4750 load thiếu thông tin thủ thuật (BV Quảng ngãi)

- 🐛: Chỉnh lỗi lấy thiếu thông tin phẫu thuật, thủ thuật ![](https://i.imgur.com/pki39Uk.png)

- ☑: https://github.com/dhhiswork/Loi/issues/41
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/HospitalAdmin.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Reports.exe v.3.24.1126.1 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FReportsexe%2F32411261-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FReportsexe%2F32411261-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FReportsexe%2F32411261-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Lỗi - XML5_4750 load thiếu thông tin thủ thuật (BV Quảng ngãi)

- 🐛: Chỉnh lỗi lấy thiếu thông tin phẫu thuật, thủ thuật ![](https://i.imgur.com/pki39Uk.png)

- 🐛: Những dữ liệu XML4750 đã có phải thực hiện đối soát để cập nhật lại XML mới

- ☑: https://github.com/dhhiswork/Loi/issues/41
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Reports.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
### ☑️ KẾT QUẢ KIỂM TRA SẢN PHẨM ☑️  
## Lần 1
## Reports khi cập nhật hs130 bị trùng STT
***
> 🟥 Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.
- Diễn giải lỗi:
![ảnh](https://github.com/user-attachments/assets/f17ebf9c-48c2-4aba-91fe-e8b082bb27c7)
![ảnh](https://github.com/user-attachments/assets/1841505c-7b1f-4579-8479-7d8a5584b8e6)

**Comment by le-an-87** [comment]
### ☑️ KẾT QUẢ KIỂM TRA SẢN PHẨM ☑️  
## Lần 1
## Admin đã fix
> ✅  Hình ảnh chứng mình cho việc kiểm tra này:
![ảnh](https://github.com/user-attachments/assets/f49d424a-bfa3-41a9-bfc2-7d2ea2b449ef)

> 📘 Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
