### ISSUE TITLE
Lỗi - Fees: BV Phụ Sản: Bệnh nhân ngoại trú khám bệnh 2 ngày (48h) Fees không thống kê, không thu được chi phí ngày đầu tiên

### ISSUE THREAD

**Issue by chauthanhtra** [dhhiswork/Loi#49]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **26/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `02118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phụ Sản**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_phusan_fees_thieutien_27112024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5432`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/Ozy1JwZFB)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023108954` - _**MaKB**_: `2411016909` - _**MaBA**_: `MaBA` _**NgayKCB**_: `26/11/2024` - _**MaPhong**_: `35` - _**MaDV**_: `12` - _**ThangKT**_: `11` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Bệnh nhân thu phí nhận bệnh cấp cứu ngày 25/11/2024 có phát sinh chi phí CLS , qua ngày 26/11/2024 có phát sinh chi phí thuốc, CLS tiếp, ra viện ngày 26/11/2024 
Fees chọn ngày 26/11/2024 thì thấy bệnh nhân để thu phí nhưng phần mềm chỉ load chi phí phát sinh ngày 26/11/2024 , không thấy chi phí ngày 25/11/2024 (đã check bệnh nhân 48h)

![](https://i.imgur.com/6cAPvpe.png)
![](https://i.imgur.com/N0BmN7o.png)
![](https://i.imgur.com/NFLBD1s.png)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận và Thực hiện công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-12-03_** 

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by chauthanhtra** [comment]
Đã phát hiện nguyên nhân lỗi
Thu hồi báo lỗi

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm Fees 3.24.1126.0
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Đã tìm được nguyên nhân lỗi do bệnh nhân ngoại trú nhưng chi phí có mã bệnh án nội trú

- Hình ảnh: 

![image](https://github.com/user-attachments/assets/07168274-f824-4bb2-91ca-e57ec1c5aa6c)

**Comment by chauthanhtra** [comment]
### ✅ **HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
