### ISSUE TITLE
Lỗi - mã đối tượng = 9 bệnh nhân nội trú khi chỉnh đối tượng

### ISSUE THREAD

**Issue by le-an-87** [dhhiswork/Loi#5]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **18/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_tamphuc_18112024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  Dữ liệu test ra lỗi nên không có file backup

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024000001` - _**MaKB**_: `2411002308` - _**MaBA**_: `2024003656` _**NgayKCB**_: `18/11/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `30` - _**ThangKT**_: `11` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Trường hợp lỗi

- [ ] Trường hợp chỉnh đối tượng thu phí qua bảo hiểm có mã nơi đăng ký ban đầu ngoài tỉnh -> madt = 9
- [ ] Trường hợp chỉnh đối tượng thu phí sang chuyển viện -> madt = 1.2

![ảnh](https://github.com/user-attachments/assets/842c9139-fab4-4747-a7d9-1917f732f617)
Mã đối tượng 9
![ảnh](https://github.com/user-attachments/assets/4a523ef6-5fbd-4c5a-af38-5b1ab5c6ff93)
Mã đối tượng = 1.2
![ảnh](https://github.com/user-attachments/assets/8c71d93b-49a7-4295-bf25-2168a4373213)
![ảnh](https://github.com/user-attachments/assets/e4d08df7-5f3d-4acd-8339-33988600510b)

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận.
⌛ Thời gian hoàn thành dự kiến: 2024-11-19

**Comment by vuongdh** [comment]
@le-an-87 BV tâm Phúc là BV tuyến mấy vậy em?

**Comment by vuongdh** [comment]
Dữ liệu có ghi nhận theo mô tả này không Ân:

![image](https://github.com/user-attachments/assets/343653e7-586e-468d-88d5-cbee38bad809)

![image](https://github.com/user-attachments/assets/f4d2a735-dff0-4e68-b0ce-4eb86979c666)

**Comment by vuongdh** [comment]
![image](https://github.com/user-attachments/assets/69ad7a89-469b-4d3a-8194-bf5b5560a9ba)

**Comment by vuongdh** [comment]
![image](https://github.com/user-attachments/assets/cf091231-349a-4611-b8e4-22162bca61a2)

**Comment by vuongdh** [comment]
Để anh test lại theo mô tả mới

**Comment by vuongdh** [comment]
Cập nhật theo [mô tả 4750](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/Mô%20tả%20XML130%20-%20Bổ%20sung%20QĐ%204750.md#user-content-fnref-2024-08-03-03-28965e09757aa84c16925032c8c9fe4d)

![image](https://github.com/user-attachments/assets/d8e5578b-68ca-4aab-a9dd-a767706ffadf)

![image](https://github.com/user-attachments/assets/83e9ace6-1d3f-4972-ade1-67c2eb9c941b)

![image](https://github.com/user-attachments/assets/3e450bfe-07a2-4d7c-8db2-425b55dfec6f)

[Link tải (NAS)]()

**Comment by le-an-87** [comment]
### ❓ TRAO ĐỔI ❓ 
❔ Câu hỏi: này là fix rồi hay chưa anh @vuongdh?
không thấy ghi nhận module hay gì hết vậy anh.
***

**Comment by vuongdh** [comment]
@le-an-87 fix rồi đó em, do cách cũ tính cùng tuyến/trái tuyến theo: tham số trong tỉnh, tham số tuyenbv, thông tư 627, thông tư 40
--> bản cập nhật fix lại theo: mô tả 4750 (cách ghi nhận này, mới khớp với file xml 4750)

**Comment by vuongdh** [comment]
> ### ❓ TRAO ĐỔI ❓
> không thấy ghi nhận module hay gì hết vậy anh.
@le-an-87 Em đang báo lỗi - mã đối tượng = 9 **bệnh nhân nội trú khi chỉnh đối tượng**

**Comment by le-an-87** [comment]
### ☑️ KẾT QUẢ KIỂM TRA SẢN PHẨM ☑️  
## Lần 1
> 🟥 Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.
- Diễn giải lỗi: chức năng chỉnh đối tượng không load lên bệnh viện để chọn
![ảnh](https://github.com/user-attachments/assets/8a61c67e-4d6c-4f74-97eb-46188cbe6d6f)
![Treatment_RUDF9pq7kp](https://github.com/user-attachments/assets/9d2d3f17-9f3f-46d4-bbe3-0804738c30c4)

**Comment by le-an-87** [comment]
### 🚨 CHƯA HOÀN THÀNH 🚨 
✅  Hoàn thành kiểm tra
🚨 Phần mềm chưa đáp ứng đúng yêu cầu.
***

**Comment by vuongdh** [comment]
Fix lỗi: không hiển thị danh sách bệnh viện đăng ký khi chỉnh đối tượng

Hình ảnh:
![image](https://github.com/user-attachments/assets/3c8fc51e-edf6-4f8a-8218-c5bb83560775)

![image](https://github.com/user-attachments/assets/b0a6eae4-ef63-48fd-9b69-eda8fa1f8b10)


[Link tải (NAS)](https://gofile.me/78TQg/5cy6yBgf0)

**Comment by le-an-87** [comment]
### ☑️ KẾT QUẢ KIỂM TRA SẢN PHẨM ☑️  
## Lần 2
## XML4750 sau khi chỉnh đối tượng có mã đối tượng = 9

> 🟥 Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.
- Diễn giải lỗi: XML4750 có mã đối tượng = 9
![ảnh](https://github.com/user-attachments/assets/4e565539-386a-477e-89d7-c3ebd9ef517c)
![ảnh](https://github.com/user-attachments/assets/6c2f821d-c0ce-4adf-93ae-ee7106b7b418)
***

**Comment by le-an-87** [comment]
### 🚨 CHƯA HOÀN THÀNH 🚨 
✅  Hoàn thành kiểm tra
🚨 Phần mềm chưa đáp ứng đúng yêu cầu.
***

**Comment by vuongdh** [comment]
Phản hồi không đủ thông tin, đề nghị làm rõ lỗi ở module nào?
Treatment: ghi nhận dữ liệu có đúng theo mô tả hay không?

**Comment by vuongdh** [comment]
mã đối tượng = 9 ==> do module Admin hiển thị

**Comment by le-an-87** [comment]
### ❓ TRAO ĐỔI ❓ 
❔ Câu hỏi: trường hợp xml4750 mã đối tượng = 9 có giải quyết không anh @tolaptrinh-issue?

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Kiểm tra lại thông tin, sau khi chỉnh thông tin xem đúng mô tả MA_DOITUONG_KCB chưa. Nếu đúng theo mô tả mà Admin lấy sai thì kiểm tra để xong luồng công việc._**

- **⏳ Thời gian hoàn thành:** **_2024-12-02_** 

- **🧑‍💻 Thực hiện:** @vuongdh 

- **🧑‍💻 Thảo luận:** @le-an-87 : ***Tổ lập trình sẽ kiểm tra lại.***

---

<sup>**📢Lưu ý tiếp nhận:**</sup>
<sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
<sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
<sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
<sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by vuongdh** [comment]
Treatment đã thực theo:
Cập nhật theo [mô tả 4750](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/Mô%20tả%20XML130%20-%20Bổ%20sung%20QĐ%204750.md#user-content-fnref-2024-08-03-03-28965e09757aa84c16925032c8c9fe4d)

![image](https://github.com/user-attachments/assets/d8e5578b-68ca-4aab-a9dd-a767706ffadf)

![image](https://github.com/user-attachments/assets/83e9ace6-1d3f-4972-ade1-67c2eb9c941b)

Nhóm test: Test đã xem đáp ứng theo mô tả chưa

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @vuongdh 
- **📘 Nội dung:** Khi sản phẩm của tổ hoàn thành thì mới nhờ Nhóm Hỗ trợ hoặc Triển khai kiểm thứ nhé, anh hãy chứng minh sản phẩm mình đã đúng thì mới nhờ kiểm thử.

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận.
⌛ Thời gian hoàn thành dự kiến: 2024-12-04

Module cập nhật: chỉnh đối tượng theo mô tả 
Cập nhật theo [mô tả 4750](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/Mô%20tả%20XML130%20-%20Bổ%20sung%20QĐ%204750.md#user-content-fnref-2024-08-03-03-28965e09757aa84c16925032c8c9fe4d)

![image](https://github.com/user-attachments/assets/d8e5578b-68ca-4aab-a9dd-a767706ffadf)

![image](https://github.com/user-attachments/assets/83e9ace6-1d3f-4972-ade1-67c2eb9c941b)

==> Module Treatment cập nhật theo mô tả là hoàn thành.
Hiển thị sai mã đối tượng là module Admin.  Nên tách 2 issue

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Treatment.exe v.4.24.1204.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42412040-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42412040-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42412040-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Lỗi - mã đối tượng = 9 bệnh nhân nội trú khi chỉnh đối tượng

- BV Tâm Phúc (60152)

- Tham số tuyenbv = 2

- Tham số: thetrongtinh = 1

- Trường hợp BN ngoài tỉnh:

- Mã BVĐK (92007)

- Bệnh nhân: maba = 2024003659

-psdangky.giayxacnhancutru = 0

![image](https://github.com/user-attachments/assets/42423179-aaf2-45dd-8a88-9affb80a28c1)

==> BN ngoài tỉnh:

==> trái tuyến được hưởng như cùng tuyến

==> tuyen = 0, tuyenxml = 1

![image](https://github.com/user-attachments/assets/9cc80405-ea53-4396-8a66-2cf374a44912)

- mô tả:

![image](https://github.com/user-attachments/assets/0d7324d9-be41-4a24-afbb-78979e29e63c)

- Kết quả:

![image](https://github.com/user-attachments/assets/24ab2d61-2350-4cef-a89a-530bc297fdfe)

- Trường hợp BN trong tỉnh:

- Bệnh nhân: maba = 2024003656

- Mã BVĐK (60022)

==> BN trong tỉnh:

- Mô tả:

![image](https://github.com/user-attachments/assets/5294d08c-b841-4054-9442-afdf5a6b01d4)

- Kể quả:

![image](https://github.com/user-attachments/assets/41d555e2-ee99-4ae6-96c5-5a38f6d6117c)

- ☑: https://github.com/dhhiswork/Loi/issues/5
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Treatment.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by vuongdh** [comment]
📣 Treatment.exe v.4.24.1204.0 ⬇️OneDrive (https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42412040-OneDrive.json) ⬇️GoogleStorage (https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42412040-GoogleStorage.json) ⬇️NasDHSolutions (https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42412040-NasDHSolutions.json)

**Comment by le-an-87** [comment]
### ☑️ KẾT QUẢ KIỂM TRA SẢN PHẨM ☑️  
## Lần 3
> 🟥 Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.
- Diễn giải lỗi:
- [ ] Lỗi không load được danh mục ICD khi lập phiếu thủ thuật
![ảnh](https://github.com/user-attachments/assets/048aa404-776d-41a9-a161-0ec545343879)
![ảnh](https://github.com/user-attachments/assets/c54e13d5-c8b5-47f0-b1b2-fdc377599383)
![ảnh](https://github.com/user-attachments/assets/2cd893f4-0669-4550-a806-2e8b330955a1)

**Comment by vuongdh** [comment]
Lỗi phát sinh không dính tới git này thì tạo git lỗi khác đi em, cho dễ theo dõi.
