### ISSUE TITLE
Lỗi - NƠI CẤP CỦA CMND TRONG FROM HIỆU CHỈNH THÔNG TIN

### ISSUE THREAD

**Issue by minhduc2it** [dhhiswork/Loi#52]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ĐỨC**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92085`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tâm Thần**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_tamthan`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/LSsPsKCCS

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024008629` - _**MaKB**_: `2410002634` - _**NgayKCB**_: `28/11/2024` - _**ThangKT**_: `11` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

- [ ] https://github.com/dhhiswork/YeuCau/issues/18

NƠI CẤP CỦA CMND TRONG FROM HIỆU CHỈNH THÔNG TIN
Module: ADMIN - REGISTER - PRESCRIPTION - PRINTER
Khi đăng ký không nhập ngày Cấp CCCD

![image](https://github.com/user-attachments/assets/eba3e45b-6d5e-48a8-b6c1-e219be3d039d)

Nhưng trong dữ liệu dmbenhnhan.ngaycap = lấy ngày hiện tại **(Để rỗng ngày cấp khi không chọn)**

![image](https://github.com/user-attachments/assets/00ad6004-f764-4502-9f51-a2ee0bbe1da7)

Hiệu chỉnh thông tin ô Ngày cấp load ngày hiện tại
![image](https://github.com/user-attachments/assets/e4011207-8348-4d63-93de-785730124853)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận và Thực hiện công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-12-02_** 

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 HospitalRegister.exe v.3.24.1128.1 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F32411281-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F32411281-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F32411281-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Lỗi - NƠI CẤP CỦA CMND TRONG FROM HIỆU CHỈNH THÔNG TIN

- 🐛: Chỉnh lỗi khi không chọn ngày cấp vẫn lưu có giá trị ![](https://i.imgur.com/YrrrAV3.png) ![](https://i.imgur.com/MDrZc69.png)

- ☑: https://github.com/dhhiswork/Loi/issues/52
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/HospitalRegister.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by minhduc2it** [comment]
✅**HOÀN THÀNH** ✅
     🆗 Kết quả kiểm tra đạt yêu cầu
     👉 Các chức năng khác chưa ghi nhận bất thường
---
Đã kiểm tra thành công
![image](https://github.com/user-attachments/assets/20b3e892-e0e3-4eca-8157-79925aa6c878)

**Comment by minhduc2it** [comment]
⁉️** TRAO ĐỔI ** ⁉️
@tolaptrinh-issue  Cập nhật lại Hiệu chỉnh thông tin 3 module: ADMIN - PRESCRIPTION - PRINTER như Register đã fix bên trên
---

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @minhduc2it 
- **📘 Nội dung:** Nhờ kiểm thử lại chức năng này giúp, nảy có kiểm tra code đã có xử lý trường hợp này rồi.

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by minhduc2it** [comment]
✅**HOÀN THÀNH** ✅
     🆗 Kết quả kiểm tra đạt yêu cầu
     👉 Các chức năng khác chưa ghi nhận bất thường
---
Hiệu chỉnh thông tin trên Admin
![image](https://github.com/user-attachments/assets/28c038f5-3821-48a4-b26e-893656433dc7)

Hiệu chỉnh thông tin trên PRESCRIPTION
![image](https://github.com/user-attachments/assets/177adb7e-a7e9-4cbd-8c2c-6898711a915c)

Hiệu chỉnh thông tin trên PRINTER
![image](https://github.com/user-attachments/assets/351b4ba5-2ac7-4c68-8acc-aa127d2c3eba)
