### ISSUE TITLE
Lỗi - Test: Prescription chỉnh toa thuốc phần mềm tự ghi nhận trạng thái tái khám

### ISSUE THREAD

**Issue by chauthanhtra** [dhhiswork/Loi#53]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_qdy_ct_mau25_khonglaythuoc_29102024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5432`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/iYEWTTmp7)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024011796` - _**MaKB**_: `2410000006` - _**MaBA**_: `MaBA` _**NgayKCB**_: `27/11/2024` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `10` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Prescription khi chỉnh toa thuốc lưu lại thì phần mềm tự ghi nhận psdangky.taikham = 1
-> nếu Printer in không lấy thuốc thì sẽ không in được bảng kê

![](https://i.imgur.com/2mxBmbp.gif)

**Comment by le-an-87** [comment]
### ❓ TRAO ĐỔI ❓ 
❔ Câu hỏi: cung cấp thêm thông tin giá trị tham số **taikham** nhe

**Comment by chauthanhtra** [comment]
Tham số taikham = 0
![](https://i.imgur.com/TOMwDiZ.png)

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @nghitamhongngoc @nghivanbi 
- **📘 Nội dung:** Hỗ trợ Tổ lập trình vấn đề này, chức năng tái khám (tương tự hẹn ngày thanh toán), tới hạn thanh toán thì mới in phiếu 01 được.

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by nghivanbi** [comment]
💡 TRAO ĐỔI💡
---------------------------------------------------------------------
-  👉 **Assign**: @tolaptrinh-issue 
-  📘 **Nội dung**:
- Tham số này lúc trước để hỗ trợ các bệnh nhân khám lao để tổng hợp chi phí 2 lần khám. Về cơ bản hiện tại tham số này không có tác dụng đối với tất cả các module.
- Rà soát lại code liên quan để xóa tham số này khỏi tham số hệ thống.

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận và Thực hiện công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Rà soát không sử dụng tham số `taikham` và không sử dụng trạng thái `taikham` trong current.psdangky._**

- **⏳ Thời gian hoàn thành:** **_2024-12-03_** 

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 HospitalPrinter.exe v.3.24.1128.2 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalPrinterexe%2F32411282-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalPrinterexe%2F32411282-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalPrinterexe%2F32411282-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Lỗi - Test: Prescription chỉnh toa thuốc phần mềm tự ghi nhận trạng thái tái khám

- ✨: Loại bỏ chức năng hẹn thanh toán (taikham) khi thực hiện thao tác in phiếu, không lấy thuốc ![](https://i.imgur.com/MijYnf7.png) ![](https://i.imgur.com/8SUPv9o.png)

- ☑: https://github.com/dhhiswork/Loi/issues/53
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/HospitalPrinter.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### ✔️ **ĐÃ TIẾP NHẬN**
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '6/12/2024'.

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm HospitalPrinter.exe v.3.24.1129.0
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Printer In không lấy thuốc đã in được bảng kê cho bệnh nhân có trạng thái taikham = 1

- Hình ảnh: 

![](https://i.imgur.com/RlGQ1LI.gif)

***

**Comment by chauthanhtra** [comment]
### ✅ **HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
