### ISSUE TITLE
Lỗi - Lưu kết quả CĐHA bị lỗi

### ISSUE THREAD

**Issue by lqbinh1987** [dhhiswork/Loi#54]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92086`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Ung Bướu**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_ungbuou_pacs`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/SlKCwxyJ7)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024053682` - _**MaKB**_: `2411006918` - _**MaBA**_: `MaBA` _**NgayKCB**_: `28/11/2024` - _**MaPhong**_: `001` - _**MaDV**_: `10` - _**ThangKT**_: `11` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Khi lưu kết quả XQ, phần mềm báo lỗi như hình, vẫn lưu kết quả được. Nhưng kết quả cũng như mô tả không gửi được qua được hệ thống PACs
![image](https://github.com/user-attachments/assets/b2f673f6-191f-48b0-8550-d3cf26a5ed13)

![image](https://github.com/user-attachments/assets/308bb8e2-02f2-4b0c-a2ca-0b0ee2ff21a2)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-12-02_** 

- **🧑‍💻 Thực hiện:** @vinh-dh 

---

<sup>**📢Lưu ý tiếp nhận:**</sup>
<sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
<sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
<sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
<sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by vinh-dh** [comment]
✔️ Đã tiếp nhận.
⏳ Thời gian hoàn thành dự kiến: 2024-12-02.

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Diagnose.exe v.3.24.1201.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FDiagnoseexe%2F32412010-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FDiagnoseexe%2F32412010-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FDiagnoseexe%2F32412010-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Sửa lỗi khi lưu kết quả (kết nối PACS Vĩnh Phát).

- ☑: https://github.com/dhhiswork/Loi/issues/54
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Diagnose.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by lqbinh1987** [comment]
🐛  **Đã fix lỗi**
-Test lần: 1 
![image](https://github.com/user-attachments/assets/ec6d9f5c-97b1-43f3-a76a-ccc2b4fa269d)
