### ISSUE TITLE
Lỗi - Test: Printer In không lấy thuốc và In bệnh nhân không ký tên không lấy được XML130 lên Reports và XML4750 lên Admin, in ngày cũ phần mềm ghi nhận ngày in là ngày hiện tại 

### ISSUE THREAD

**Issue by chauthanhtra** [dhhiswork/Loi#55]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_qdy_ct_mau25_khonglaythuoc_29102024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5432`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/7GqRjANc4)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
- In không lấy thuốc
   > _**MaBN**_: `2024011799` - _**MaKB**_: `2410000009` - _**MaBA**_: `MaBA` _**NgayKCB**_: `27/11/2024` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `10` - _**NamKT**_: `2024`
- In bệnh nhân không ký tên
   > _**MaBN**_: `2024011801` - _**MaKB**_: `2410000011` - _**MaBA**_: `MaBA` _**NgayKCB**_: `27/11/2024` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `10` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

1. In bệnh nhân ngày cũ nhưng phần mềm không hỏi cập nhật ngày kết thúc khám mà in trực tiếp và ghi nhập ngày in là ngày giờ hiện tại không phải ngày đăng ký (psdangky.ngayinphieu)

2. Dữ liệu current.psxml và dữ liệu trong xml130 không ghi nhận ngay_ttoan nên phần mềm Admin và Reports không lấy được dữ liệu XML4750 để báo cáo

![](https://i.imgur.com/aRPFZxY.gif)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận và Thực hiện công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Thực hiện kiểm thử và chỉnh lỗi nếu có trên Module Printer, không thực hiện trên Prescription._**

- **⏳ Thời gian hoàn thành:** **_2024-12-03_** 

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 HospitalPrinter.exe v.3.24.1128.3 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalPrinterexe%2F32411283-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalPrinterexe%2F32411283-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalPrinterexe%2F32411283-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Lỗi - Test: Prescription In không lấy thuốc và In bệnh nhân không ký tên không lấy được XML130 lên Reports và XML4750 lên Admin, in ngày cũ phần mềm ghi nhận ngày in là ngày hiện tại

- 🐛: Thêm chức năng cập nhật giờ kết thúc khi Không lấy thuốc khác ngày. ![](https://i.imgur.com/1J5tkbS.png) ![](https://i.imgur.com/GQ04rGl.png) ![](https://i.imgur.com/oSjWSEH.png)

- ☑: https://github.com/dhhiswork/Loi/issues/55
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/HospitalPrinter.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### ✔️ **ĐÃ TIẾP NHẬN**
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '6/12/2024'.

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm HospitalPrinter.exe v.3.24.1129.0
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Printer đã fix lỗi không hiện form cho cập nhật ngày in phiếu
  - Printer đã fix lỗi không ghi nhận ngày thanh toán XML không lấy được XML lên Admin và Reports

- Hình ảnh: 
- ![](https://i.imgur.com/t0BVSPE.gif)
[![](https://i.imgur.com/Ldbr9ktm.jpg)](https://i.imgur.com/Ldbr9kt.gif)

![](https://i.imgur.com/Ldbr9kt.gif)

[https://i.imgur.com/Ldbr9kt.gif](https://i.imgur.com/Ldbr9kt.gif)

![](https://i.imgur.com/y9aR5Gp.png)

![](https://i.imgur.com/A9OdPYR.png)
![](https://i.imgur.com/ilKY5pF.png)
![](https://i.imgur.com/c4pzIa8.png)
***

**Comment by chauthanhtra** [comment]
### ✅ **HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
