### ISSUE TITLE
Lỗi - Prescription Tờ điều trị in ra không hiển thị cận lâm sàng theo diễn biến

### ISSUE THREAD

**Issue by hvtuan1987** [dhhiswork/Loi#6]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **18/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92004`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BVĐK TP Cần Thơ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbtpct_bant_todieutri`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/MBHUs1NXp)
###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2021065250` - _**MaKB**_: `2410029040` - _**MaBA**_: `N2024012246` _**NgayKCB**_: `15/11/2024` - _**MaPhong**_: `49` - _**MaDV**_: `31` - _**ThangKT**_: `11` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)

 Xem quá trình điều trị của bệnh nhân có chỉ định cận lâm sàng nhưng khi bấm In thì Tờ điều điều trị cột Y lệnh không hiển thị cận lâm sàng đã chỉ định 
Hình khi xem quá trình điều trị
![image](https://github.com/user-attachments/assets/bf7228e9-cca1-414e-8ce2-acf0a39d042a)

Hình khi bấm nút in
![image](https://github.com/user-attachments/assets/9e1e611f-9e43-454d-86eb-4ffaa1536483)

Hình đúng khi có xem quá trình điều trị ngày 13/11/2024 và in ra
![image](https://github.com/user-attachments/assets/7a0ca910-3da3-422b-94d7-be2077160e9d)
![image](https://github.com/user-attachments/assets/79166cb6-c7a7-4a5e-b6d9-6d70d1f06b4b)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-11-22_** 

- **🧑‍💻 Thực hiện:** @lequocthong29 

---

<sup>**📢Lưu ý tiếp nhận:**</sup>
<sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
<sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
<sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
<sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-11-22.

**Comment by lequocthong29** [comment]
📣
-----------------
@hvtuan1987 Kiểm tra lại nha a.  
Theo mô tả [Mo-ta-cho-phep-nhap-them-y-lenh-trong qua trinh dieu tri](https://github.com/dhhiswork/Mo-ta-he-thong/blob/main/Vuong-Mo-ta-cho-phep-nhap-them-y-lenh-trong%20qua%20trinh%20dieu%20tri.md). Khi in quá trình điều trị: Y lệnh sẽ lấy từ qtdieutrin.ylenh (nếu có) ngược lại lấy từ chỉ định cls, thuốc

**Comment by hvtuan1987** [comment]
-  ✔️ **Để anh hướng dẫn người dùng lại !**
