### ISSUE TITLE
Lỗi - chức năng hỗ trợ lấy ngày tái khám theo ngày uống toa thuốc (PK Đông Tây)

### ISSUE THREAD

**Issue by le-an-87** [dhhiswork/Loi#60]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#
-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **29/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_dongtay_mabenh_kt_29112024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5432`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_dongtay_mabenh_kt_29112024`](https://gofile.me/78TQg/lXeXBs2tj)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024000001` - _**MaKB**_: `2411016693` - _**MaBA**_: `MaBA` _**NgayKCB**_: `29/11/2024` - _**MaPhong**_: `H27` - _**MaDV**_: `K17` - _**ThangKT**_: `11` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Bệnh ngoại trú Lỗi chức năng hỗ trợ lấy ngày tái khám bằng số ngày uống toa thuốc:

- [ ] Khi thêm toa lần 2 trở lên phần mềm không ghi ngày tái khám.
- [ ] Lỗi Form hiển thị không chỉnh toa lick vào số ngày uống và lick chuột sang khu vực khác thì tự động hiển thị ngày tái khám.

Video thao tác 2 lỗi trên
![Prescription_AD8WTBcVyd](https://github.com/user-attachments/assets/bf3d9d7f-15a0-4571-82ef-ff514f4e3dec)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-12-02_** 

- **🧑‍💻 Thực hiện:** @lequocthong29 

---

<sup>**📢Lưu ý tiếp nhận:**</sup>
<sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
<sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
<sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
<sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-12-02.

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Prescription.exe v.3.24.1202.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32412020-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32412020-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32412020-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Lỗi - chức năng hỗ trợ lấy ngày tái khám theo ngày uống toa thuốc (PK Đông Tây)

![](https://i.imgur.com/5kFQREC.gif)

- ☑: https://github.com/dhhiswork/Loi/issues/60
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Prescription.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
### ☑️ KẾT QUẢ KIỂM TRA SẢN PHẨM ☑️  
## Lần 1
> 🟥 Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.
- Diễn giải lỗi:
- [ ]  Lỗi khi xóa toa thuốc và thêm toa mới.
- [ ]  khi chỉnh hạn tái khám -> ngày hẹn không chạy theo.
![Prescription_0eALOX1xCO](https://github.com/user-attachments/assets/c583be95-de5d-4a10-9ce1-d1d77e5c05db)
![Prescription_U3wQk9MDl1](https://github.com/user-attachments/assets/80e48cae-4613-482b-8d93-941b97ad000e)

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @lequocthong29 
- **📘 Nội dung:** Xem chỉnh lỗi theo thông tin Tổ hỗ trợ kiểm thử 

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Prescription.exe v.3.24.1204.4 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32412044-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32412044-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32412044-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Lỗi ngày hẹn tái khám khi xóa toa thuốc và thêm toa mới

![](https://i.imgur.com/lPAR1Ih.gif)

- 🐛: khi chỉnh hạn tái khám -> ngày hẹn không chạy theo (Lưu ý: hiện tại phần mềm chỉ cập nhật ngày hẹn tái khám mới khi ngày hẹn đó lớn hơn ngày hẹn hiện tại.)

![](https://i.imgur.com/PFA5Y2z.gif)

- ☑: https://github.com/dhhiswork/Loi/issues/60
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Prescription.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
### ☑️ KẾT QUẢ KIỂM TRA SẢN PHẨM ☑️  
## Lần 2
> ✅  Hình ảnh chứng mình cho việc kiểm tra này:
![Prescription_toBc5ujhaM](https://github.com/user-attachments/assets/05449c6b-4200-4d04-97dd-42415072d5e6)

> 📘 Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***

**Comment by le-an-87** [comment]
### **HoànThành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
