### ISSUE TITLE
Lỗi - Ô Môn: XML4750.MA_BENH_KT lấy mã bệnh YHCT

### ISSUE THREAD

**Issue by chauthanhtra** [dhhiswork/Loi#66]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **3/12/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92007`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Ô Môn**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_omon_mabenhkt_yhct_03122024_1`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5432`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/5Ow6itXz8)
-  ![module](https://img.shields.io/badge/Phân%20hệ%20báo%20lỗi-:-blue?style=plastic&logo=github) `Admin, Prescription, Reports`

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2019047362` - _**MaKB**_: `2411011663` - _**MaBA**_: `N2024007964` _**NgayKCB**_: `29/11/2024` - _**MaPhong**_: `13` - _**MaDV**_: `11` - _**ThangKT**_: `11` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

MA_BENH_KT lấy mã bệnh YHCT ( mã bệnh YHCT đã có ở trường MA_BENH_YHCT ) bệnh nhân BANT theo đợt chỉ có mã bệnh chính và mã bệnh YHCT của mã bệnh chính
-> Admin, Prescription fix lỗi xuất XML
-> Đề nghị Admin, Reports hỗ trợ cập nhật lại XML

![](https://i.imgur.com/iYqz9Mf.png)
![](https://i.imgur.com/g11A8Yb.png)
![](https://i.imgur.com/DkLcWrm.png)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Kiểm tra lại thông tin lỗi với các phiên bản mới nhất, cái này hôm trước nhớ đã hoàn thành rồi.._**

- **⏳ Thời gian hoàn thành:** **_2024-12-03_** 

- **🧑‍💻 Thực hiện:** @nqhoa1005 

---

<sup>**📢Lưu ý tiếp nhận:**</sup>
<sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
<sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
<sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
<sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by chauthanhtra** [comment]
###  ❌ **HỦY BÁO LỖI**

Đã tìm được nguyên nhân lỗi do Prescription cũ ghi nhận mã bệnh YHCT vào bnnoitru.maicdpxml
-> có thể cập nhật lại bằng cách vào xem bảng kê tổng kết chi phí 

![](https://i.imgur.com/GSLsvDU.png)

Xem lại bảng kê
![](https://i.imgur.com/BxLZGzc.png)
![](https://i.imgur.com/Azvir7a.png)

**Comment by chauthanhtra** [comment]
### ✅ **HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
