### ISSUE TITLE
Lỗi - chức năng gửi xml4750 (BV Ô Môn)

### ISSUE THREAD

**Issue by le-an-87** [dhhiswork/Loi#69]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **04/12/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_omon_guixml_04122024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5432`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_omon_guixml_04122024`](https://gofile.me/78TQg/DknTZozFY)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024037833` - _**MaKB**_: `2412001486` - _**MaBA**_: `2024016147` _**NgayKCB**_: `04/12/2024 7:45:00 SA` - _**MaPhong**_: `PH7` - _**MaDV**_: `01` - _**ThangKT**_: `12` - _**NamKT**_: `2024`
   > _**MaBN**_: `2019065624` - _**MaKB**_: `2412003363` - _**MaBA**_: `MaBA` _**NgayKCB**_: `04/12/2024 8:28:33 SA` - _**MaPhong**_: `NGOAI` - _**MaDV**_: `03` - _**ThangKT**_: `12` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Lỗi chức năng gửi XML4750.
khi gửi phần mềm báo lỗi: KHÔNG THỂ LẤY PHIÊN LÀM VIỆC: EMPTY access_token, id_token. Response: {"maKetQua":"401","APIKey":null}

```
![ảnh](https://github.com/user-attachments/assets/14b3146a-4301-4d3d-b501-fd99ce6659c2)
[an_omon_guixml_04122024.log](https://github.com/user-attachments/files/18001691/an_omon_guixml_04122024.log)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận và Thực hiện công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-12-06_** 

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.1205.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalAdminexe%2F32412050-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalAdminexe%2F32412050-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalAdminexe%2F32412050-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Lỗi - chức năng gửi xml4750 (BV Ô Môn)

- 🐛: Bổ sung ghi nhận chi tiết lỗi khi gửi Hồ sơ 4750 khi gửi gặp lỗi, chi tiết

```

05/12/2024 08:15:36: AGiamDinhAPIERROR: KHÔNG THỂ LẤY PHIÊN LÀM VIỆC: EMPTY access_token, id_token. Response: . Options: {username:92007_BV,passwordHash:09E4A8C7E1C3B47D40F2B935D0E0BEF5,url:https://egw.baohiemxahoi.gov.vn,tokenResource:/api/token/take,hosoXMLResource:/api/qd130/guiHoSoXmlQD4750,checkInResource:/api/qd130/checkInKcbQd4750}

DebugOTH.exe

DebugOTH.exe

1.24.1031.1

```

- ☑: https://github.com/dhhiswork/Loi/issues/69
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/HospitalAdmin.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @le-an-87 
- **📘 Nội dung:** Kiểm thử lại, xem lấy đúng với thông tin cấu hình hay không. Còn việc gửi này phụ thuộc vào IP của bệnh viện nữa, nên Phần mềm hỗ trợ kiểm tra xem lấy đúng cấu hình để thực hiện gửi hay không.

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by le-an-87** [comment]
### ☑️ KẾT QUẢ KIỂM TRA SẢN PHẨM ☑️  
## Lần 1

> 🟥 Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.
- Diễn giải lỗi:
![ảnh](https://github.com/user-attachments/assets/ea692e25-28c7-4327-8f60-08de460ab968)
![ảnh](https://github.com/user-attachments/assets/23226eed-3e1d-4f42-9f87-f66e408780bc)
***

**Comment by le-an-87** [comment]
### 🚨 CHƯA HOÀN THÀNH 🚨 
✅  Hoàn thành kiểm tra
🚨 Phần mềm chưa đáp ứng đúng yêu cầu.
***

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.1205.2 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalAdminexe%2F32412052-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalAdminexe%2F32412052-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalAdminexe%2F32412052-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Lỗi - chức năng gửi xml4750 (BV Ô Môn)

- 🐛: Chỉnh lỗi lấy sai thông tin cấu hình khi gửi hồ sơ XML4750

- ☑: https://github.com/dhhiswork/Loi/issues/69
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/HospitalAdmin.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
### ☑️ KẾT QUẢ KIỂM TRA SẢN PHẨM ☑️  
## Lần 2
> ✅  Hình ảnh chứng mình cho việc kiểm tra này:
![ảnh](https://github.com/user-attachments/assets/b724200e-ee25-4421-9f6e-e49a42c29a73)
![ảnh](https://github.com/user-attachments/assets/4f2cb290-4346-4c29-88cd-36fe645d7fe3)
![ảnh](https://github.com/user-attachments/assets/0b129727-4dcc-4c04-9e1b-5c51ffc4f06f)
![ảnh](https://github.com/user-attachments/assets/5eef9370-ca08-463a-88c4-b851cf71eca7)

**Comment by le-an-87** [comment]
### **HoànThành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
