### ISSUE TITLE
Lỗi - Chỉnh đối tượng bệnh nhân nội trú Treatment (BV Ung Bướu)

### ISSUE THREAD

**Issue by le-an-87** [dhhiswork/Loi#70]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **04/12/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92086`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Ung Bướu**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_ungbuou_chinhdt_04122024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5432`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_ungbuou_chinhdt_04122024`](https://gofile.me/78TQg/KjEN6GE0S)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024056303` - _**MaKB**_: `2412000446` - _**MaBA**_: `025085` _**NgayKCB**_: `04/12/2024` - _**MaPhong**_: `N13` - _**MaDV**_: `05` - _**ThangKT**_: `12` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
BV Ung bướu tuyencmkt = 2
bệnh nhân có thẻ bhyt đăng ký tại bệnh viện 89001 tuyencmkt = 3
-> không chỉnh được bệnh nhân sang trạng thái - trái tuyến được hưởng như cùng tuyến.
```
![ảnh](https://github.com/user-attachments/assets/8b8279d9-a060-4950-a470-78180c274dc3)
![ảnh](https://github.com/user-attachments/assets/998617a0-f9be-4a20-94f2-914b02fe9d98)
![ảnh](https://github.com/user-attachments/assets/a9ab18ba-139c-4605-91f5-c7c564eb1596)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-12-04_** 

- **🧑‍💻 Thực hiện:** @vuongdh 

---

<sup>**📢Lưu ý tiếp nhận:**</sup>
<sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
<sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
<sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
<sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by vuongdh** [comment]
Trường hợp này cũng giống nhưng https://github.com/dhhiswork/YeuCau/issues/35. Mô tả thiếu trường hợp. Chờ cập nhật mô tả bổ sung

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @vuongdh 
- **📘 Nội dung:** Cập nhật mô tả bổ sung luôn. Có vướng mắc thì trao đổi với a @vinh-dh 

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận: mô tả bổ sung và fix lỗi
⌛ Thời gian hoàn thành dự kiến: 2024-12-06

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Treatment.exe v.4.24.1205.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42412050-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42412050-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42412050-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Yêu cầu - Treament ghi nhận lại lý do vào viện bệnh nhân trái tuyến nội trú

- 🐛: Lỗi - Chỉnh đối tượng bệnh nhân nội trú Treatment (BV Ung Bướu)

- Cập nhật theo mô tả bổ xung:

![image](https://github.com/user-attachments/assets/ceb367e1-1e89-4a9a-9036-5baeeeebf002)

![image](https://github.com/user-attachments/assets/716ea853-a86d-4c4e-ab40-4987f9e9a48c)

![image](https://github.com/user-attachments/assets/fdc4a620-18ec-4e0a-a6a6-456e7eb06354)

- ☑: https://github.com/dhhiswork/Loi/issues/70

- ☑: https://github.com/dhhiswork/YeuCau/issues/35
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Treatment.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
### ☑️ KẾT QUẢ KIỂM TRA SẢN PHẨM ☑️  
## Lần 1
> ✅  Hình ảnh chứng mình cho việc kiểm tra này:
![ảnh](https://github.com/user-attachments/assets/9334ec35-94f7-49bf-a0bc-651ede618c5d)
![ảnh](https://github.com/user-attachments/assets/d2666d9b-f2ff-4c90-8bd5-f03802567bff)
![ảnh](https://github.com/user-attachments/assets/b2911e04-0c15-442e-a953-10f1e4fe89e4)
![ảnh](https://github.com/user-attachments/assets/da15dee4-b80b-4938-937b-8328b507fd6c)
![ảnh](https://github.com/user-attachments/assets/97f273ad-6cce-4bff-a30a-074947beaafd)

> 📘 Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***

**Comment by le-an-87** [comment]
### **HoànThành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
