### ISSUE TITLE
Lỗi - Phiếu nghỉ ốm lấy sai thời gian Từ ngày

### ISSUE THREAD

**Issue by lqbinh1987** [dhhiswork/Loi#72]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **04/12/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `ALL`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **ALL**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_phuoclongbli`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5432`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](NAS/DuLieuCongTy/Database/binh_phuoclongbli2024000001_2411000001_2024005579.rar)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Hiện tại khi lập phiếu nghỉ ốm, **Từ ngày** tự động lấy ngày xuất viện +1 ngày, như hình dưới, như vậy khi gửi cổng báo lỗi.
![image](https://github.com/user-attachments/assets/fd5b533b-db36-4952-b0ca-068fdb898b24)
![image](https://github.com/user-attachments/assets/8963f9b4-07e3-4c65-8818-f78330a24095)

Chú ý: Ngoại trú thì đang lấy đúng theo quy định là ngày khám bệnh.
![image](https://github.com/user-attachments/assets/11cefd57-bdc1-446a-9735-5d50650876c5)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận và Thực hiện công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-12-09_** 

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @lqbinh1987 
- **📘 Nội dung:** Hiện tại chức năng này, phần mềm đã cho phép người dùng thay đổi. Nên việc gửi chưa phù hợp với cổng thì người dùng phải thực hiện chỉnh lại. Phần mềm sẽ hỗ trợ thêm chức năng, khi lập Phiếu nghỉ ốm sẽ lấy mặc định là ngày khám bệnh.

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @lqbinh1987 @nghitamhongngoc @nghivanbi 
- **📘 Nội dung:** Nhờ tìm hiểu thêm phần ngày hưởng chế độ nghỉ ốm này, trường hợp khám bệnh, thì ngày bắt đầu nghỉ ốm là ngày khám bệnh. Còn điều trị nội trú, thì ngày hưởng nghỉ ốm là ngày nhập viện, hay là ngày ra viện để thực hiện hoàn chỉnh hơn.

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by tolaptrinh-issue** [comment]
### <sub>❌ Từ chối tiếp nhận<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Lý do:** Không đủ thông tin để hỗ trợ

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by lqbinh1987** [comment]
💡 TRAO ĐỔI💡
---------------------------------------------------------------------
-  👉 **Assign**: @tolaptrinh-issue 
-  📘 **Nội dung**: Đang trao đổi với BV, hiện tại nhiều BV bị lỗi này, có nhờ BV hỏi giám định thì giám định cũng không biết, vui lòng chờ...

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @lqbinh1987 
- **📘 Nội dung:** Khó khăn thì đóng luồng này lại. Mở luồng mới. Cái này Tổ lập trình ghi nhận là Từ chối tiếp nhận rồi. 

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by lqbinh1987** [comment]
Đã chuyển [git mới](https://github.com/dhhiswork/YeuCau/issues/41)
