### ISSUE TITLE
Lỗi - Prescription: BV Lấp Vò lỗi khi cấp toa thuốc

### ISSUE THREAD

**Issue by chauthanhtra** [dhhiswork/Loi#75]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **6/12/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87005`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT HUYỆN LẤP VÒ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_lapvo_loicaptoa_06122024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5432`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/OOmfhdrfj)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2018039025` - _**MaKB**_: `2412002789` - _**MaBA**_: `MaBA` _**NgayKCB**_: `5/12/2024` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `12` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Prescription 3.24.1205.3
Lỗi khi cấp toa thuốc

![](https://i.imgur.com/scvbcIa.png)
![](https://i.imgur.com/lpBhT4F.png)
![](https://i.imgur.com/moqAnoi.png)
![](https://i.imgur.com/0I1fZOT.png)

**Comment by le-an-87** [comment]
chạy lại script này rồi thử lại nhe @chauthanhtra 

DO $$ 
    BEGIN
        BEGIN
            ALTER TABLE current.tkdatatemp ADD COLUMN da_can_kho NUMERIC(1,0);
        EXCEPTION
            WHEN duplicate_column THEN RAISE NOTICE 'Cot <da_can_kho> da co trong table <tkdatatemp>.';
        END;
    END;
$$;

**Comment by chauthanhtra** [comment]
> chạy lại script này rồi thử lại nhe @chauthanhtra
> 
> DO $$ BEGIN BEGIN ALTER TABLE current.tkdatatemp ADD COLUMN da_can_kho NUMERIC(1,0); EXCEPTION WHEN duplicate_column THEN RAISE NOTICE 'Cot <da_can_kho> da co trong table .'; END; END; $$;

### ⁉️ **THẢO LUẬN**
***
Được rồi mà có cập nhật script này lên Admin không?
hay cập nhật tay cho BV

**Comment by le-an-87** [comment]
Cập nhật cho bv thôi. do lỗi cập nhật script của admin hà

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm Prescription 3.24.1205.3
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Đã fix được lỗi cập toa thuốc

- Hình ảnh: 
![](https://i.imgur.com/wucfKWu.png)

![](https://i.imgur.com/Mq7Zzov.gif)


***

**Comment by chauthanhtra** [comment]
### ✅ **HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
