### ISSUE TITLE
Lỗi - Prescription: BV Phụ Sản Toa vật tư kèm theo không lấy được thuốc từ tủ trực nhà thuốc

### ISSUE THREAD

**Issue by chauthanhtra** [dhhiswork/Loi#78]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **7/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phụ Sản CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_phusan_toavtyt_tutrucnhathuoc_kthaythuoc_07112024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/nnsxuQF7k)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

Lỗi ghi lại: https://github.com/dh-his/Ghi_Nhan_Loi/issues/41

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024043467` - _**MaKB**_: `2411004273` - _**MaBA**_: `MaBA` _**NgayKCB**_: `7/11/2024` - _**MaPhong**_: `36` - _**MaDV**_: `15` - _**ThangKT**_: `11` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `13` - _**KhoLe**_: `13` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Prescription -> Chỉ định CLS -> Vật tư kèm theo -> Chọn tủ trực nhà thuốc -> không lấy được danh sách thuốc tủ trực nhà thuốc

Toa VTYT kèm theo trên Prescription không lấy được thuốc từ tủ trực nhà thuốc

![](https://i.imgur.com/iYDPXld.png)

- Cấp toa thường lấy được thuốc tủ trực nhà thuốc

![](https://i.imgur.com/BSlXwpt.png)

- Cấp toa VTYT kèm theo không lấy được thuốc tủ trực nhà thuốc
![](https://i.imgur.com/iLl7nbH.png)

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST 4**
***
Phần mềm Prescription.exe v.3.24.1128.5
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Prescription đã fix lỗi 
    - Khi cấp toa VTYT lấy thuốc từ kho thì khi chọn thuốc lần đầu thì phần mềm đóng form chọn thuốc rồi mở lại bắt chọn lại thuốc
    - Không thấy thuốc từ kho tủ trực BHYT bình thường -> không cấp được toa
    - Đã cấp được toa VT tủ trực nhà thuốc

- Hình ảnh: 
![](https://i.imgur.com/QUE5Ow2.gif)
![](https://i.imgur.com/x5tOjjm.gif)


***

### 🆘 **Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.**

- Diễn giải lỗi:
  - Hiện tại các dữ liệu của các đơn vị khác không có triển khai tủ trực nhà thuốc cũng dùng được toa tủ trực nhà thuốc
- Hình ảnh lỗi:
BV QDY CT
![](https://i.imgur.com/UTIKsUA.gif)

PK Minh Quang
![](https://i.imgur.com/sQmkjlP.gif)

***

Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
![](https://i.imgur.com/u5remWX.png)

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST 5 **
***
Phần mềm Prescription.exe v.3.24.1205.1
***
### 🆘 **Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.**

- Diễn giải lỗi:
  - Không cấp được toa VT kèm theo lấy thuốc từ tủ trực bình thường, không thấy thuốc khi chọn tủ trực bình thường (lỗi này phần mềm trước không bị). lỗi lập đi lập lại nhiều lần fix xong thì bị lại
- Hình ảnh lỗi:
![](https://i.imgur.com/WtEBdJh.gif)


***
Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-12-15_** 

- **🧑‍💻 Thực hiện:** @lequocthong29 

---

<sup>**📢Lưu ý tiếp nhận:**</sup>
<sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
<sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
<sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
<sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-12-15.

**Comment by lequocthong29** [comment]
@chauthanhtra 
- Diễn giải lỗi:
Không cấp được toa VT kèm theo lấy thuốc từ tủ trực bình thường, không thấy thuốc khi chọn tủ trực bình thường (lỗi này phần mềm trước không bị). lỗi lập đi lập lại nhiều lần fix xong thì bị lại.
 => Trường hợp này test lại trên bản Pre mới nhất nha a. E kiểm tra thấy không lỗi.
![](https://i.imgur.com/AWFdE6F.gif).

- Diễn giải lỗi:
Hiện tại các dữ liệu của các đơn vị khác không có triển khai tủ trực nhà thuốc cũng dùng được toa tủ trực nhà thuốc.
 => Trường hợp này hiện tại bệnh viện nào có tủ trực nhà thuốc đều sử dụng được.

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm Prescription.exe v.3.24.1217.0
***
### 🆘 **Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.**

- Diễn giải lỗi:
  - Vẫn còn lỗi : nhờ code kiểm tra xem dữ liệu này cấu hình sai thông tin gì
  - Dữ liệu: tra_phusan_toavtyt_tutrucnhathuoc_kthaythuoc_07112024 
  - port: 5432
  - bệnh nhân ngày 28/11/2024
- Hình ảnh lỗi:
![](https://i.imgur.com/1tW4UuT.png)
![](https://i.imgur.com/g6LtKe4.gif)


***
Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-12-18.

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Prescription.exe v.3.24.1218.2 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32412182-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32412182-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32412182-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Lỗi - Prescription: BV Phụ Sản Toa vật tư kèm theo không lấy được thuốc từ tủ trực nhà thuốc

![](https://i.imgur.com/eCCqZht.gif)

- ☑: https://github.com/dhhiswork/Loi/issues/78
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Prescription.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm Prescription.exe v.3.24.1219.0
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Phần mềm Prescription đã fix lỗi cấp toa VTYT lấy thuốc tử tủ trực, tủ trực nhà thuốc

- Hình ảnh: 
![](https://i.imgur.com/byyJ9Rb.gif)
![](https://i.imgur.com/FCtue4c.gif)
![](https://i.imgur.com/Ij5DS5m.png)
![](https://i.imgur.com/oScN8V8.png)

***

**Comment by chauthanhtra** [comment]
### ✅ **HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
