### ISSUE TITLE
Lỗi - Register gọi bệnh chưa theo mô tả

### ISSUE THREAD

**Issue by hvtuan1987** [dhhiswork/Loi#83]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **12/12/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87179`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Trung tâm y tế TP Sa Đéc**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_ttytsadec_goibenh`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/bV3vU5L72)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024002226` - _**MaKB**_: `2410001977` - _**MaBA**_: `2024046454` _**NgayKCB**_: `12/12/2024` - _**MaPhong**_: `01` - _**MaDV**_: `01` - _**ThangKT**_: `10` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
Hiện tại Register gọi bệnh của bệnh viện không qua phân khu (Đơn vị không triển khai Kios)
Chức năng đã sử dụng tại Bệnh viện trước giờ
1.Bấm vào nút Next để gọi bệnh tiếp theo (Mời bệnh nhân có số thứ tự từ.. đến... vào quầy tiếp nhận) 
2. Bấm vào Micro để gọi lại bệnh cần gọi. (Mời bệnh nhân có số thứ tự từ.. đến... vào quầy tiếp nhận) 
 Yêu cầu :
Thay đổi câu gọi như sau: Mời khách hàng có số thứ tự từ.. đến... vào quầy tiếp nhận (Thay từ Bệnh nhân thành khách hàng)

Do lúc trước có yêu cầu chức năng này cho đơn vị nhưng git cũ lỗi nên không tìm thấy thông tin
Hình cấu hình tại Register
![image](https://github.com/user-attachments/assets/6e1cfb87-6a8f-4e4f-9cf2-5631740673b6)

Hình cấu hình tại Speaker
![image](https://github.com/user-attachments/assets/108b53c4-7a25-492e-b797-f31a1c384af0)

Link tham khảo của tổ code đã hướng dẫn nhưng kiểm tra chức năng chưa đúng yêu cầu: [https://github.com/dhhiswork/Mo-ta-he-thong/blob/main/Thong-mo-ta-cau-hinh-cach-doc-goi-benh-tren-speaker.md](url)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Thay đổi cách gọi theo mô tả. Nếu không cấu theo mô tả, thực hiện theo cách hiện tại._**

- **⏳ Thời gian hoàn thành:** **_2024-12-14_** 

- **🧑‍💻 Thực hiện:** @lequocthong29 

---

<sup>**📢Lưu ý tiếp nhận:**</sup>
<sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
<sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
<sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
<sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-12-14.

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 HospitalRegister.exe v.3.24.1213.4 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F32412134-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F32412134-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F32412134-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Lỗi - Register gọi bệnh chưa theo mô tả

- 📕: Cập nhật gọi bệnh trên Register giống với mô tả https://github.com/dhhiswork/Mo-ta-he-thong/blob/main/Thong-mo-ta-cau-hinh-cach-doc-goi-benh-tren-speaker.md

- ☑: https://github.com/dhhiswork/Loi/issues/83
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/HospitalRegister.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by hvtuan1987** [comment]
## 📣 @lequocthong
Hiện bảng Register này vẫn gọi chưa đúng theo yêu cầu !
Vẫn còn giọng đọc mời bệnh nhân chứ không phải mời khách hàng

**Comment by lequocthong29** [comment]
@hvtuan1987 Anh có thêm 2 file đọc vào thư mục cài đặt như mô tả ko a.
![image](https://github.com/user-attachments/assets/f120a585-b142-43a5-8776-ed3374ba39c7)

**Comment by hvtuan1987** [comment]
@lequocthong29  Có chớ ! 
![image](https://github.com/user-attachments/assets/d1854e2e-b983-41d5-9dba-517da1a1f626)

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @hvtuan1987 
- **📘 Nội dung:** Đang bàn ở Register, chụp hình Speaker.

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by hvtuan1987** [comment]
@tolaptrinh-issue Theo mô tả thì file âm thanh để trong thư mục Speaker á !

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 HospitalRegister.exe v.3.24.1214.1 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F32412141-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F32412141-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F32412141-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Lỗi - Register gọi bệnh chưa theo mô tả.

- 🐛: Fix lỗi phần gọi bệnh từ số... đến số....

- ☑: https://github.com/dhhiswork/Loi/issues/83
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/HospitalRegister.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by lequocthong29** [comment]
cập nhật [mô tả gọi bệnh](https://github.com/dhhiswork/Mo-ta-he-thong/blob/main/Thong-mo-ta-cau-hinh-cach-doc-goi-benh-tren-speaker.md)  
![](https://i.imgur.com/WrDuNGk.png)

**Comment by hvtuan1987** [comment]
-  ✔️ **Xác nhận** 
Register đã hỗ trợ theo yêu cầu
