### ISSUE TITLE
Lỗi - Bảng kê 6556 lấy luôn chi phí không thanh toán BHYT (BV Tâm Phúc)

### ISSUE THREAD

**Issue by le-an-87** [dhhiswork/Loi#88]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **16/12/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `60152`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tâm phúc**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_tamphuc_12_12122024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5432`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_tamphuc_12_12122024`](https://gofile.me/78TQg/viu0H1ACq)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022022662` - _**MaKB**_: `N2024001538` - _**MaBA**_: `2412003709`- _**NgayKCB**_: `12/12/2024 7:42:56 SA` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `12` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `01` - _**MaHH**_: `S271` 

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bảng kê 6556 cấu hình chỉ lấy chi phí thuộc BHYT
-> khi in vẫn lấy các chi phí không thanh BHYT
```
![ảnh](https://github.com/user-attachments/assets/9df8d9cb-0edc-4888-94d1-2b0c3b86d94d)
![ảnh](https://github.com/user-attachments/assets/a30c94e7-0045-4c6a-b133-974acf92f42e)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận và Thực hiện công việc<sup><sup>[HD.05]</sup></sup></sub>
  
  ---
  
  - **📘 Mô tả thực hiện:**
    - [ ] ***Theo luồng công việc này.*** 
  
  - **⏳ Thời gian hoàn thành:** **_2024-12-23_** 
  
  - **🧑‍💻 Thực hiện:** @tolaptrinh-issue  
  
  ---
  
  <sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 HospitalPrinter.exe v.3.24.1217.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalPrinterexe%2F32412170-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalPrinterexe%2F32412170-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalPrinterexe%2F32412170-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Lỗi - Bảng kê 6556 lấy luôn chi phí không thanh toán BHYT (BV Tâm Phúc) ![](https://i.imgur.com/uZC9CBA.png)

- ☑: https://github.com/dhhiswork/Loi/issues/88
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/HospitalPrinter.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
### ☑️ KẾT QUẢ KIỂM TRA SẢN PHẨM ☑️  
## Lần 1
> ✅  Hình ảnh chứng mình cho việc kiểm tra này.
![ảnh](https://github.com/user-attachments/assets/215a0052-7df3-4ff4-a009-d249f189cfc6)
![ảnh](https://github.com/user-attachments/assets/50cf8550-a186-4817-a714-b02314cc85c6)

**Comment by le-an-87** [comment]
### **HoànThành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
