### ISSUE TITLE
Lỗi - Không thể hiện nội dung thiết kế trang in bảng kê thanh toán không tiền mặt.

### ISSUE THREAD

**Issue by lqbinh1987** [dhhiswork/Loi#90]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **13/12/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `ALL Khách hàng sử dụng QR`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **ALL Khách hàng sử dụng QR**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_sannhitv_trangin`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5432`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`NAS/DuLieuCongTy/Database/bvsn2024034280_2412002818_.rar`]

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `ALL` - _**MaKB**_: `ALL` - _**MaBA**_: `ALL` _**NgayKCB**_: `16/12/2024` - _**MaPhong**_: `ALL` - _**MaDV**_: `ALL` - _**ThangKT**_: `12` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Trong thiết kế trang in hầu như các para không thể hiện được giá trị trên trang in.

![image](https://github.com/user-attachments/assets/ed2a1d76-452b-47e2-95d1-60fd8daa3b29)

![image](https://github.com/user-attachments/assets/9ef12cf7-3ba6-4226-b4cd-e9428e71a745)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận và Thực hiện công việc<sup><sup>[HD.05]</sup></sup></sub>
  
  ---
  
  - **📘 Mô tả thực hiện:**
    - [ ] ***Theo luồng công việc này.*** 
  
  - **⏳ Thời gian hoàn thành:** **_2024-12-23_** 
  
  - **🧑‍💻 Thực hiện:** @tolaptrinh-issue  
  
  ---
  
  <sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @lqbinh1987
- **📘 Nội dung:** Do cấu hình sai báo cáo nên những thông tin này không lên được. Hướng dẫn tạo báo cáo theo hướng dẫn dưới đây: ![](https://i.imgur.com/r1Ev72z.png) ![](https://i.imgur.com/CzluYsA.png)

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by lqbinh1987** [comment]
✅ **Đã hỗ trợ**
-Test lần:1
![image](https://github.com/user-attachments/assets/b10f0faf-7bb8-422b-bf2e-4d105d44b975)
![image](https://github.com/user-attachments/assets/e27933cd-e289-4468-8565-a0a7127dea5e)
