### ISSUE TITLE
Lỗi - Chạy runner gửi BN HIV bị lỗi.

### ISSUE THREAD

**Issue by lqbinh1987** [dhhiswork/Loi#91]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **16/12/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả BV Chạy HIV`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả BV Chạy HIV**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_bvcr_hiv_3`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5432`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`NAS/DuLieuCongTy/Database/bvcr_hiv_3.rar`]

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**2020006412**_: `MaBN` - _**MaKB**_: `2409009857` - _**MaBA**_: `N2020001020` _**NgayKCB**_: `27/09/2024` - _**MaPhong**_: `42` - _**MaDV**_: `01` - _**ThangKT**_: `09` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Khi chạy theo lịch tự động hoặc chạy thủ công, đang chạy gửi dữ liệu thì xuất hiện lỗi như hình đầu tiên đồng thời **ngừng chạy luôn**, chạy lại thêm lần nữa thì thành công cho BN đó, hoặc cũng có thể xuất hiện lỗi khác như hình 2, rồi chạy thêm lần nữa thì mới thành công bệnh nhân đó, nhưng nó lại xảy ra lỗi tương tự ở bệnh nhân khác.
Trường hợp này xảy ra ở BN Thu Phí và Miễn Phí.

![image](https://github.com/user-attachments/assets/76474317-3577-4e54-8d26-81815e63b4c3)
![image](https://github.com/user-attachments/assets/5c227640-f95f-470b-a02a-fb3332ba4619)
![image](https://github.com/user-attachments/assets/c20947b7-42b2-48f6-9afc-3503762d685f)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận và Thực hiện công việc<sup><sup>[HD.05]</sup></sup></sub>
  
  ---
  
  - **📘 Mô tả thực hiện:**
    - [ ] ***Theo luồng công việc này.*** 
  
  - **⏳ Thời gian hoàn thành:** **_2024-12-23_** 
  
  - **🧑‍💻 Thực hiện:** @tolaptrinh-issue  
  
  ---
  
  <sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @lqbinh1987
- **📘 Nội dung:** Đã cập nhật ![](https://i.imgur.com/f4ZJMTL.png)

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by lqbinh1987** [comment]
💡KIỂM TRA SẢN PHẨM💡
***
Assignees: @tolaptrinh-issue 
❌Chưa đạt.

Mô tả lỗi:  Hiện tại khi chạy thủ công hoặc chạy theo lịch thì vẫn còn lỗi như mô tả ở trên.

![image](https://github.com/user-attachments/assets/5f3a04cb-9588-4ae0-90b5-4af6f91ef80c)


***
Thông tin bệnh nhân(nếu có)
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `bvbinhthuy_loi_guihiv`
-  ![ten_csdl](https://img.shields.io/badge/Port-:-blue?style=plastic&logo=github) `5432`
- ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) (`NA/DuLieuCongTy/Database/bvbinhthuy_loi_guihiv.rar`)
   > _**MaBN**_: `2017018400` - _**MaKB**_: `2412006419` - _**MaBA**_: `MaBA` _**NgayKCB**_: `18/12/2024` - _**MaPhong**_: `ARV1` - _**MaDV**_: `KSDB` - _**ThangKT**_: `12` - _**NamKT**_: `2024`

***
❌ Tạm dừng kiểm tra kiểm tra đối với module chưa đạt yêu cầu.

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @lqbinh1987
- **📘 Nội dung:** Kiểm tra lại máy chạy runner
- ***Lỗi do git không thực hiện cập nhật được. Phải thực hiện chạy lệnh này cho Runner `git config --global --add safe.directory D:/DH-ARV/src-send4750`***. Thông tin lỗi: ![](https://i.imgur.com/zU9uzVL.png)
- ***Cập nhật thành công sẽ có thông tin phiên bản đang thực thi*** ![](https://i.imgur.com/4l4iluJ.png)

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @lqbinh1987
- **📘 Nội dung:** Đã cập nhật thêm chức năng để chỉnh lại lỗi này và thực hiện chạy lại ngày 18/12/2024. Nhờ @lqbinh1987 theo dõi xem còn bị lỗi khi gửi bệnh nhân.? ![](https://i.imgur.com/fG0Wjy2.png)

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by lqbinh1987** [comment]
🐛  **Đã fix lỗi**
- Theo dõi mấy ngày qua thì không còn xuất hiện lỗi nữa, cả gửi tự động theo lịch hoặc gửi thủ công.
-Test lần:
![image](https://github.com/user-attachments/assets/dd4c144e-2036-4e9e-83bf-c9efaf9ad3f3)
![image](https://github.com/user-attachments/assets/731674bf-2fbf-4bfd-85d7-c6c0afcb678b)
![image](https://github.com/user-attachments/assets/3b12ba5b-fac0-4bc2-a343-e52369cbe52f)
